import Foundation

public let zoneInitManagedBlockBegin = "# BEGIN WINMUX ZONE INIT MANAGED BLOCK"
public let zoneInitManagedBlockEnd = "# END WINMUX ZONE INIT MANAGED BLOCK"

public enum ZoneInitConfigEditStatus: Equatable, Sendable {
    case appended
    case replaced
    case unchanged
}

public struct ZoneInitConfigEditResult: Equatable, Sendable {
    public let updatedText: String
    public let status: ZoneInitConfigEditStatus

    public init(updatedText: String, status: ZoneInitConfigEditStatus) {
        self.updatedText = updatedText
        self.status = status
    }
}

public struct ZoneInitConfigValidation: Equatable, Sendable {
    public let hasActiveZones: Bool

    public init(hasActiveZones: Bool) {
        self.hasActiveZones = hasActiveZones
    }
}

public struct ZoneInitColumnDefinition: Equatable, Sendable {
    public let id: String
    public let name: String?
    public let width: Double

    public init(id: String, name: String?, width: Double) {
        self.id = id
        self.name = name
        self.width = width
    }
}

public struct ZoneInitPresetDefinition: Equatable, Sendable {
    public let defaultZoneId: String
    public let columns: [ZoneInitColumnDefinition]

    public init(defaultZoneId: String, columns: [ZoneInitColumnDefinition]) {
        self.defaultZoneId = defaultZoneId
        self.columns = columns
    }
}

public func zoneInitPresetDefinition(_ preset: ZoneInitPreset) -> ZoneInitPresetDefinition {
    switch preset {
        case .balanced:
            ZoneInitPresetDefinition(defaultZoneId: "main", columns: [
                ZoneInitColumnDefinition(id: "left", name: "Reference", width: 0.25),
                ZoneInitColumnDefinition(id: "main", name: "Work", width: 0.50),
                ZoneInitColumnDefinition(id: "right", name: "Comms", width: 0.25),
            ])
        case .focusOnly:
            ZoneInitPresetDefinition(defaultZoneId: "main", columns: [
                ZoneInitColumnDefinition(id: "left", name: "Reference", width: 0.15),
                ZoneInitColumnDefinition(id: "main", name: "Work", width: 0.70),
                ZoneInitColumnDefinition(id: "right", name: "Comms", width: 0.15),
            ])
        case .commsOpen:
            ZoneInitPresetDefinition(defaultZoneId: "main", columns: [
                ZoneInitColumnDefinition(id: "left", name: "Reference", width: 0.20),
                ZoneInitColumnDefinition(id: "main", name: "Work", width: 0.55),
                ZoneInitColumnDefinition(id: "right", name: "Comms", width: 0.25),
            ])
        case .dashboard:
            ZoneInitPresetDefinition(defaultZoneId: "main", columns: [
                ZoneInitColumnDefinition(id: "left", name: "Reference", width: 0.20),
                ZoneInitColumnDefinition(id: "main", name: "Work", width: 0.45),
                ZoneInitColumnDefinition(id: "right", name: "Comms", width: 0.20),
                ZoneInitColumnDefinition(id: "dashboard", name: "Dashboard", width: 0.15),
            ])
    }
}

public func renderZoneInitManagedBlock(
    preset: ZoneInitPreset,
    presetDefinition: ZoneInitPresetDefinition,
    monitorId: Int,
) -> String {
    var output = [
        zoneInitManagedBlockBegin,
        "# Generated by: winmux zone init --preset \(preset.rawValue) --write",
        "[[zones]]",
        "monitor = \(monitorId)",
        "layout = 'columns'",
        "default-zone = \(zoneInitTomlBasicString(presetDefinition.defaultZoneId))",
        "columns = [",
    ]
    for column in presetDefinition.columns {
        var fields = [
            "id = \(zoneInitTomlBasicString(column.id))",
        ]
        if let name = column.name {
            fields.append("name = \(zoneInitTomlBasicString(name))")
        }
        fields.append("width = \(zoneInitFormatTomlFloat(column.width))")
        output.append("    { \(fields.joined(separator: ", ")) },")
    }
    output.append("]")
    output.append(zoneInitManagedBlockEnd)
    return output.joined(separator: "\n")
}

public func renderZoneInitOutput(
    title: String,
    mode: String,
    preset: ZoneInitPreset,
    monitorSummary: String,
    backupPath: String?,
    block: String,
) -> [String] {
    var output = [
        title,
        "Mode: \(mode)",
        "Preset: \(preset.rawValue)",
        "Selected monitor: \(monitorSummary)",
    ]
    if let backupPath {
        output.append("Backup: \(backupPath)")
    }
    output.append("TOML:")
    output.append(block)
    if mode == "dry-run" {
        output.append("Run with --write to update the config.")
    }
    return output
}

@MainActor
public func applyZoneInitManagedBlockToConfigText(
    to configText: String,
    block: String,
    replaceExisting: Bool,
    validateConfig: @MainActor (String) -> Result<ZoneInitConfigValidation, String>,
) -> Result<ZoneInitConfigEditResult, String> {
    if let existingRangeResult = zoneInitManagedBlockRange(in: configText) {
        switch existingRangeResult {
            case .failure(let message):
                return .failure(message)
            case .success(let range):
                let existingBlock = String(configText[range])
                if existingBlock.trimmingCharacters(in: .whitespacesAndNewlines) ==
                    block.trimmingCharacters(in: .whitespacesAndNewlines)
                {
                    return .success(ZoneInitConfigEditResult(updatedText: configText, status: .unchanged))
                }
                guard replaceExisting else {
                    return .failure("A WinMux-managed zone init block already exists. Re-run with --replace-existing to update it.")
                }
                var updated = configText
                updated.replaceSubrange(range, with: block)
                return validateZoneInitConfigEdit(updatedText: updated, status: .replaced, validateConfig: validateConfig)
        }
    }

    switch validateConfig(configText) {
        case .failure(let message):
            return .failure("Config must parse before zone init can edit it:\n\(message)")
        case .success(let validation):
            guard !validation.hasActiveZones else {
                return .failure(
                    "Config already has active [[zones]]. " +
                        "zone init will not overwrite unmanaged zones; remove them or use save/export commands for existing layouts.",
                )
            }
    }

    let lineSeparator = configText.contains("\r\n") ? "\r\n" : "\n"
    let prefix: String
    if configText.isEmpty {
        prefix = ""
    } else if configText.hasSuffix(lineSeparator) {
        prefix = lineSeparator
    } else {
        prefix = lineSeparator + lineSeparator
    }
    let updated = configText + prefix + block + lineSeparator
    return validateZoneInitConfigEdit(updatedText: updated, status: .appended, validateConfig: validateConfig)
}

public func nextZoneInitBackupUrl(for url: URL) -> URL {
    let stamp = zoneInitBackupTimestamp()
    let baseName = "\(url.lastPathComponent).backup-\(stamp)"
    let directory = url.deletingLastPathComponent()
    var candidate = directory.appending(component: baseName)
    var suffix = 2
    while FileManager.default.fileExists(atPath: candidate.path) {
        candidate = directory.appending(component: "\(baseName)-\(suffix)")
        suffix += 1
    }
    return candidate
}

public func zoneInitBackupTimestamp(date: Date = Date()) -> String {
    let formatter = DateFormatter()
    formatter.calendar = Calendar(identifier: .gregorian)
    formatter.locale = Locale(identifier: "en_US_POSIX")
    formatter.timeZone = TimeZone(secondsFromGMT: 0)
    formatter.dateFormat = "yyyyMMdd'T'HHmmss'Z'"
    return formatter.string(from: date)
}

public func zoneInitFormatTomlFloat(_ value: Double) -> String {
    var text = String(format: "%.6f", locale: Locale(identifier: "en_US_POSIX"), value)
    while text.last == "0" {
        text.removeLast()
    }
    if text.last == "." {
        text.append("0")
    }
    return text == "-0.0" ? "0.0" : text
}

@MainActor
private func validateZoneInitConfigEdit(
    updatedText: String,
    status: ZoneInitConfigEditStatus,
    validateConfig: @MainActor (String) -> Result<ZoneInitConfigValidation, String>,
) -> Result<ZoneInitConfigEditResult, String> {
    switch validateConfig(updatedText) {
        case .failure(let message):
            return .failure("Edited config would not parse:\n\(message)")
        case .success(let validation):
            guard validation.hasActiveZones else {
                return .failure("Edited config did not add an active [[zones]] block")
            }
            return .success(ZoneInitConfigEditResult(updatedText: updatedText, status: status))
    }
}

private func zoneInitManagedBlockRange(in configText: String) -> Result<Range<String.Index>, String>? {
    guard let begin = configText.range(of: zoneInitManagedBlockBegin) else { return nil }
    guard configText.range(of: zoneInitManagedBlockBegin, range: begin.upperBound..<configText.endIndex) == nil else {
        return .failure("Config contains multiple WinMux-managed zone init block starts")
    }
    guard let end = configText.range(of: zoneInitManagedBlockEnd, range: begin.upperBound..<configText.endIndex) else {
        return .failure("Config contains a WinMux-managed zone init block start without an end marker")
    }
    guard configText.range(of: zoneInitManagedBlockEnd, range: end.upperBound..<configText.endIndex) == nil else {
        return .failure("Config contains multiple WinMux-managed zone init block ends")
    }
    return .success(begin.lowerBound..<end.upperBound)
}

private func zoneInitTomlBasicString(_ value: String) -> String {
    var result = "\""
    for scalar in value.unicodeScalars {
        switch scalar {
            case "\"": result += "\\\""
            case "\\": result += "\\\\"
            case "\n": result += "\\n"
            case "\t": result += "\\t"
            case "\r": result += "\\r"
            default: result.unicodeScalars.append(scalar)
        }
    }
    result += "\""
    return result
}
