VERSION ?= 0.0.0-SNAPSHOT
CODESIGN_IDENTITY ?= Apple Development
EXPECTED_CODESIGN_AUTHORITY ?= Apple Development: zxzimeng@gmail.com (4F7GA4MB42)
DEVELOPMENT_TEAM ?= W9C2P3N7Q2
RELEASE_DIR ?= .release
RELEASE_TAG ?= v$(VERSION)
RELEASE_NOTES ?= auto
PUBLISH ?= 1
APP_INSTALL_DIR ?= /Applications
ARGS ?=

.PHONY: generate xcodeproj build build-clean run run-clean cli e2e-preflight e2e-smoke e2e-guest-smoke e2e-pre-tart-checks e2e-verify-slice e2e-verify-slice-check e2e-verify-root-demo-check e2e-package-root-demo e2e-slice-1 e2e-slice-2 e2e-slice-3 e2e-slice-4 e2e-slice-5 e2e-slice-6 e2e-slice-6b e2e-slice-8 e2e-slice-10 e2e-slice-11a release install installed clean

generate:
	/bin/bash -lc 'cd "$(CURDIR)" && \
	printf "%s\n" "// FILE IS GENERATED BY Makefile" "public let winMuxAppVersion = \"$(VERSION)\"" > Sources/Common/versionGenerated.swift && \
	git_hash="$$(git rev-parse HEAD 2>/dev/null || echo SNAPSHOT)"; \
	git_short_hash="$$(git rev-parse --short HEAD 2>/dev/null || echo SNAPSHOT)"; \
	printf "%s\n" "// FILE IS GENERATED BY Makefile" "public let gitHash = \"$$git_hash\"" "public let gitShortHash = \"$$git_short_hash\"" > Sources/Common/gitHashGenerated.swift'

xcodeproj:
	$(MAKE) generate VERSION="$(VERSION)"
	/bin/bash -lc 'cd "$(CURDIR)" && \
	source ./script/setup.sh && \
	export XCODEGEN_WINMUX_VERSION="$(VERSION)" && \
	export XCODEGEN_WINMUX_CODE_SIGN_IDENTITY="$(CODESIGN_IDENTITY)" && \
	export XCODEGEN_WINMUX_DEVELOPMENT_TEAM="$(DEVELOPMENT_TEAM)" && \
	./script/install-dep.sh --xcodegen && \
	./.deps/xcodegen/xcodegen'

build:
	$(MAKE) generate VERSION="$(VERSION)"
	/bin/bash -lc 'cd "$(CURDIR)" && \
	source ./script/setup.sh && \
	swift build && \
	swift build --target AppBundleTests && \
	rm -rf .debug && \
	mkdir .debug && \
	cp -r .build/debug/winmux .debug && \
	cp -r .build/debug/WinMuxApp .debug'

build-clean:
	/bin/bash -lc 'cd "$(CURDIR)" && rm -rf .build .debug'
	$(MAKE) build VERSION="$(VERSION)"

run:
	$(MAKE) build VERSION="$(VERSION)"
	/bin/bash -lc 'cd "$(CURDIR)" && \
	if pgrep -x yabai >/dev/null 2>&1; then echo "warning: yabai is still running and may conflict with WinMux" >&2; fi && \
	if pgrep -x skhd >/dev/null 2>&1; then echo "warning: skhd is still running; its yabai shortcuts will keep firing" >&2; fi && \
	config_path="$${WINMUX_CONFIG_PATH:-}"; \
	if [ -n "$$config_path" ]; then \
	    if [ ! -f "$$config_path" ]; then \
	        echo "Missing WinMux config: $$config_path" >&2; \
	        exit 1; \
	    fi; \
	    exec ./.debug/WinMuxApp --config-path "$$config_path" $(ARGS); \
	else \
	    exec ./.debug/WinMuxApp $(ARGS); \
	fi'

run-clean:
	$(MAKE) build-clean VERSION="$(VERSION)"
	/bin/bash -lc 'cd "$(CURDIR)" && \
	if pgrep -x yabai >/dev/null 2>&1; then echo "warning: yabai is still running and may conflict with WinMux" >&2; fi && \
	if pgrep -x skhd >/dev/null 2>&1; then echo "warning: skhd is still running; its yabai shortcuts will keep firing" >&2; fi && \
	config_path="$${WINMUX_CONFIG_PATH:-}"; \
	if [ -n "$$config_path" ]; then \
	    if [ ! -f "$$config_path" ]; then \
	        echo "Missing WinMux config: $$config_path" >&2; \
	        exit 1; \
	    fi; \
	    exec ./.debug/WinMuxApp --config-path "$$config_path" $(ARGS); \
	else \
	    exec ./.debug/WinMuxApp $(ARGS); \
	fi'

cli:
	$(MAKE) build VERSION="$(VERSION)"
	/bin/bash -lc 'cd "$(CURDIR)" && exec ./.debug/winmux $(ARGS)'

e2e-preflight:
	/bin/bash -lc 'cd "$(CURDIR)" && ./script/e2e/tart-recording-harness preflight'

e2e-smoke:
	/bin/bash -lc 'cd "$(CURDIR)" && ./script/e2e/tart-recording-harness smoke'

e2e-guest-smoke:
	/bin/bash -lc 'cd "$(CURDIR)" && WINMUX_E2E_REQUIRE_GUEST_CONTROL=1 WINMUX_E2E_CAPTURE_MODE=guest ./script/e2e/tart-recording-harness smoke'

e2e-pre-tart-checks:
	/bin/bash -lc 'cd "$(CURDIR)" && \
	guest_scripts=(script/e2e/guest/*.sh) && \
	bash -n script/e2e/tart-recording-harness && \
	bash -n script/e2e/annotate-recording && \
	bash -n script/e2e/package-root-demo && \
	bash -n script/e2e/verify-root-demo && \
	bash -n script/e2e/write-review-packet && \
	bash -n script/e2e/verify-artifact && \
	bash -n "$${guest_scripts[@]}" && \
	python3 ./script/check-command-metadata && \
	if command -v shellcheck >/dev/null 2>&1; then shellcheck script/e2e/tart-recording-harness script/e2e/annotate-recording script/e2e/package-root-demo script/e2e/verify-root-demo script/e2e/write-review-packet script/e2e/verify-artifact "$${guest_scripts[@]}"; else echo "warning: shellcheck not installed; skipping shell lint" >&2; fi && \
	./script/e2e/package-root-demo --self-test && \
	./script/e2e/verify-artifact --self-test && \
	./script/e2e/tart-recording-harness annotation-preflight && \
	./script/e2e/tart-recording-harness warmup-policy-self-test && \
	swift test --filter '"'"'ConfigTest.testParseColumnZones|ConfigTest.testParseNamedZoneLayoutPreset|ConfigTest.testParseZoneSceneWorkspaceBindings|ConfigTest.testRejectInvalidZones|ConfigTest.testRejectInvalidZoneLayoutPresetReferences|ConfigTest.testRejectInvalidZoneSceneReferences|ConfigTest.testRejectMissingZoneFields|ConfigTest.testRejectInvalidZoneIdsAndWidths|ConfigTest.testRejectDuplicateZoneMonitorSelectors|ConfigTest/testParseOnWindowDetectedZoneRouting|ListMonitorsTest|MonitorTopologyTest|ZoneCommandTest|WorkspaceSidebarDragTest/testMonitorScopesDedupeZoneViewportsByPhysicalMonitor|WorkspaceSidebarDragTest/testWorkspaceSidebarBuildsZoneTargetsForPhysicalMonitorScope|WorkspaceSidebarDragTest/testSidebarZoneTargetsResolveWithinPhysicalMonitorScopeWhenZoneIdsRepeat|WorkspaceSidebarDragTest/testSameZoneSidebarDropTargetIsNotActionable|WorkspaceSidebarDragTest/testDifferentZoneSidebarDropTargetIsActionable|WorkspaceSidebarDragTest/testMoveWindowFromSidebarToZoneMovesToZoneActiveWorkspace|WorkspaceSidebarDragTest/testMoveTabGroupFromSidebarToZoneMovesWholeGroup'"'"''

e2e-verify-slice:
	/bin/bash -lc 'cd "$(CURDIR)" && test -n "$(RUN_DIR)" && ./script/e2e/verify-artifact $(ARGS) "$(RUN_DIR)"'

e2e-verify-slice-check:
	/bin/bash -lc 'cd "$(CURDIR)" && test -n "$(RUN_DIR)" && ./script/e2e/verify-artifact --check-only $(ARGS) "$(RUN_DIR)"'

e2e-verify-root-demo-check:
	/bin/bash -lc 'cd "$(CURDIR)" && test -n "$(RUN_DIR)" && ./script/e2e/verify-root-demo $(ARGS) "$(RUN_DIR)"'

e2e-package-root-demo:
	/bin/bash -lc 'cd "$(CURDIR)" && ./script/e2e/package-root-demo $(ARGS)'

e2e-slice-1:
	$(MAKE) e2e-pre-tart-checks
	/bin/bash -lc 'cd "$(CURDIR)" && WINMUX_E2E_SLICE=slice-1 WINMUX_E2E_REQUIRE_GUEST_CONTROL=1 WINMUX_E2E_CAPTURE_MODE=guest WINMUX_E2E_RECORD_SECONDS=18 ./script/e2e/tart-recording-harness slice-1'

e2e-slice-2:
	$(MAKE) e2e-pre-tart-checks
	/bin/bash -lc 'cd "$(CURDIR)" && WINMUX_E2E_SLICE=slice-2 WINMUX_E2E_REQUIRE_GUEST_CONTROL=1 WINMUX_E2E_CAPTURE_MODE=guest WINMUX_E2E_RECORD_SECONDS=28 ./script/e2e/tart-recording-harness slice-2'

e2e-slice-3:
	$(MAKE) e2e-pre-tart-checks
	/bin/bash -lc 'cd "$(CURDIR)" && WINMUX_E2E_SLICE=slice-3 WINMUX_E2E_REQUIRE_GUEST_CONTROL=1 WINMUX_E2E_CAPTURE_MODE=guest WINMUX_E2E_RECORD_SECONDS=36 ./script/e2e/tart-recording-harness slice-3'

e2e-slice-4:
	$(MAKE) e2e-pre-tart-checks
	/bin/bash -lc 'cd "$(CURDIR)" && WINMUX_E2E_SLICE=slice-4 WINMUX_E2E_REQUIRE_GUEST_CONTROL=1 WINMUX_E2E_CAPTURE_MODE=guest WINMUX_E2E_RECORD_SECONDS=44 ./script/e2e/tart-recording-harness slice-4'

e2e-slice-5:
	$(MAKE) e2e-pre-tart-checks
	/bin/bash -lc 'cd "$(CURDIR)" && WINMUX_E2E_SLICE=slice-5 WINMUX_E2E_REQUIRE_GUEST_CONTROL=1 WINMUX_E2E_CAPTURE_MODE=guest WINMUX_E2E_RECORD_SECONDS=60 ./script/e2e/tart-recording-harness slice-5'

e2e-slice-6:
	$(MAKE) e2e-pre-tart-checks
	/bin/bash -lc 'cd "$(CURDIR)" && WINMUX_E2E_SLICE=slice-6 WINMUX_E2E_REQUIRE_GUEST_CONTROL=1 WINMUX_E2E_CAPTURE_MODE=guest WINMUX_E2E_RECORD_SECONDS=36 ./script/e2e/tart-recording-harness slice-6'

e2e-slice-6b:
	$(MAKE) e2e-pre-tart-checks
	/bin/bash -lc 'cd "$(CURDIR)" && WINMUX_E2E_SLICE=slice-6b WINMUX_E2E_REQUIRE_GUEST_CONTROL=1 WINMUX_E2E_CAPTURE_MODE=guest WINMUX_E2E_RECORD_SECONDS=42 ./script/e2e/tart-recording-harness slice-6b'

e2e-slice-8:
	$(MAKE) e2e-pre-tart-checks
	/bin/bash -lc 'cd "$(CURDIR)" && WINMUX_E2E_SLICE=slice-8 WINMUX_E2E_REQUIRE_GUEST_CONTROL=1 WINMUX_E2E_CAPTURE_MODE=guest WINMUX_E2E_RECORD_SECONDS=44 ./script/e2e/tart-recording-harness slice-8'

e2e-slice-10:
	$(MAKE) e2e-pre-tart-checks
	/bin/bash -lc 'cd "$(CURDIR)" && WINMUX_E2E_SLICE=slice-10 WINMUX_E2E_REQUIRE_GUEST_CONTROL=1 WINMUX_E2E_CAPTURE_MODE=guest WINMUX_E2E_RECORD_SECONDS=54 ./script/e2e/tart-recording-harness slice-10'

e2e-slice-11a:
	$(MAKE) e2e-pre-tart-checks
	/bin/bash -lc 'cd "$(CURDIR)" && WINMUX_E2E_SLICE=slice-11a WINMUX_E2E_REQUIRE_GUEST_CONTROL=1 WINMUX_E2E_CAPTURE_MODE=guest WINMUX_E2E_RECORD_SECONDS=54 ./script/e2e/tart-recording-harness slice-11a'

release:
	$(MAKE) xcodeproj VERSION="$(VERSION)" CODESIGN_IDENTITY="$(CODESIGN_IDENTITY)"
	/bin/bash -lc 'cd "$(CURDIR)" && \
	set -euo pipefail && \
	source ./script/setup.sh && \
	test -n "$(VERSION)" && \
	app_name="WinMux"; \
	release_dir="$(RELEASE_DIR)"; \
	archive_path="$$release_dir/$$app_name-$(VERSION).xcarchive"; \
	derived_data_path="$$release_dir/$$app_name-$(VERSION).deriveddata"; \
	app_path="$$archive_path/Products/Applications/$$app_name.app"; \
	zip_path="$$release_dir/$$app_name-$(VERSION).zip"; \
	log_path="$$release_dir/$$app_name-$(VERSION)-xcodebuild.log"; \
	rm -rf "$$archive_path" "$$zip_path" "$$derived_data_path"; \
	mkdir -p "$$release_dir"; \
	xcodebuild-pretty "$$log_path" \
	    -project WinMux.xcodeproj \
	    -scheme WinMux \
	    -configuration Release \
	    -archivePath "$$archive_path" \
	    -derivedDataPath "$$derived_data_path" \
	    CODE_SIGN_IDENTITY="$(CODESIGN_IDENTITY)" \
	    DEVELOPMENT_TEAM="$(DEVELOPMENT_TEAM)" \
	    CODE_SIGN_STYLE=Automatic \
	    archive; \
	test -d "$$app_path"; \
	codesign --verify --deep --strict --verbose=2 "$$app_path"; \
	codesign -dv --verbose=4 "$$app_path" 2>&1 | grep -F "Authority=$(EXPECTED_CODESIGN_AUTHORITY)" >/dev/null; \
	ditto -c -k --sequesterRsrc --keepParent "$$app_path" "$$zip_path"; \
	if [ "$(PUBLISH)" != "1" ]; then \
	    echo "Skipping GitHub release publish because PUBLISH=$(PUBLISH)"; \
	elif /usr/bin/which gh >/dev/null 2>&1; then \
	    if gh release view "$(RELEASE_TAG)" >/dev/null 2>&1; then \
	        gh release upload "$(RELEASE_TAG)" "$$zip_path" --clobber; \
	    else \
	        if [ "$(RELEASE_NOTES)" = "auto" ]; then \
	            gh release create "$(RELEASE_TAG)" "$$zip_path" --title "$$app_name $(VERSION)" --generate-notes; \
	        else \
	            gh release create "$(RELEASE_TAG)" "$$zip_path" --title "$$app_name $(VERSION)" --notes "$(RELEASE_NOTES)"; \
	        fi; \
	    fi; \
	else \
	    echo "warning: gh is not installed; built $$zip_path but did not publish a GitHub release" >&2; \
	fi'

install:
	$(MAKE) release VERSION="$(VERSION)" CODESIGN_IDENTITY="$(CODESIGN_IDENTITY)" DEVELOPMENT_TEAM="$(DEVELOPMENT_TEAM)" PUBLISH=0
	/bin/bash -lc 'cd "$(CURDIR)" && \
	set -euo pipefail && \
	app_name="WinMux"; \
	release_dir="$(RELEASE_DIR)"; \
	app_path="$$release_dir/$$app_name-$(VERSION).xcarchive/Products/Applications/$$app_name.app"; \
	install_dir="$(APP_INSTALL_DIR)"; \
	install_path="$$install_dir/$$app_name.app"; \
	test -d "$$app_path"; \
	mkdir -p "$$install_dir"; \
	osascript -e "tell application \"$$app_name\" to quit" >/dev/null 2>&1 || true; \
	rm -rf "$$install_path"; \
	ditto "$$app_path" "$$install_path"; \
	xattr -dr com.apple.quarantine "$$install_path" >/dev/null 2>&1 || true; \
	open "$$install_path"'

installed: install

clean:
	/bin/bash -lc 'cd "$(CURDIR)" && rm -rf .build .debug .deps .derived "$(RELEASE_DIR)" WinMux.xcodeproj'
