VERSION ?= 0.0.0-SNAPSHOT
CODESIGN_IDENTITY ?= Apple Development
EXPECTED_CODESIGN_AUTHORITY ?= Apple Development: zxzimeng@gmail.com (4F7GA4MB42)
DEVELOPMENT_TEAM ?= W9C2P3N7Q2
RELEASE_DIR ?= .release
RELEASE_TAG ?= v$(VERSION)
RELEASE_NOTES ?= auto
PUBLISH ?= 1
APP_INSTALL_DIR ?= /Applications
ARGS ?=

.PHONY: generate xcodeproj build build-clean run run-clean cli e2e-preflight e2e-smoke e2e-guest-smoke e2e-pre-tart-checks e2e-run-product-slice e2e-verify-slice e2e-verify-slice-check e2e-slice-closeout-check e2e-verify-root-demo-check e2e-package-root-demo e2e-slice-1 e2e-slice-2 e2e-slice-3 e2e-slice-4 e2e-slice-5 e2e-slice-6 e2e-slice-6b e2e-slice-8 e2e-slice-10 e2e-slice-11a e2e-slice-11b e2e-slice-11c e2e-slice-12 e2e-slice-13 e2e-slice-14 e2e-slice-15 e2e-slice-16 e2e-slice-17 e2e-slice-18 e2e-slice-19 e2e-slice-20 release install installed clean

generate:
	/bin/bash -lc 'cd "$(CURDIR)" && \
	printf "%s\n" "// FILE IS GENERATED BY Makefile" "public let winMuxAppVersion = \"$(VERSION)\"" > Sources/Common/versionGenerated.swift && \
	git_hash="$$(git rev-parse HEAD 2>/dev/null || echo SNAPSHOT)"; \
	git_short_hash="$$(git rev-parse --short HEAD 2>/dev/null || echo SNAPSHOT)"; \
	printf "%s\n" "// FILE IS GENERATED BY Makefile" "public let gitHash = \"$$git_hash\"" "public let gitShortHash = \"$$git_short_hash\"" > Sources/Common/gitHashGenerated.swift'

xcodeproj:
	$(MAKE) generate VERSION="$(VERSION)"
	/bin/bash -lc 'cd "$(CURDIR)" && \
	source ./script/setup.sh && \
	export XCODEGEN_WINMUX_VERSION="$(VERSION)" && \
	export XCODEGEN_WINMUX_CODE_SIGN_IDENTITY="$(CODESIGN_IDENTITY)" && \
	export XCODEGEN_WINMUX_DEVELOPMENT_TEAM="$(DEVELOPMENT_TEAM)" && \
	./script/install-dep.sh --xcodegen && \
	./.deps/xcodegen/xcodegen'

build:
	$(MAKE) generate VERSION="$(VERSION)"
	/bin/bash -lc 'cd "$(CURDIR)" && \
	source ./script/setup.sh && \
	swift build && \
	swift build --target AppBundleTests && \
	rm -rf .debug && \
	mkdir .debug && \
	cp -r .build/debug/winmux .debug && \
	cp -r .build/debug/WinMuxApp .debug'

build-clean:
	/bin/bash -lc 'cd "$(CURDIR)" && rm -rf .build .debug'
	$(MAKE) build VERSION="$(VERSION)"

run:
	$(MAKE) build VERSION="$(VERSION)"
	/bin/bash -lc 'cd "$(CURDIR)" && \
	if pgrep -x yabai >/dev/null 2>&1; then echo "warning: yabai is still running and may conflict with WinMux" >&2; fi && \
	if pgrep -x skhd >/dev/null 2>&1; then echo "warning: skhd is still running; its yabai shortcuts will keep firing" >&2; fi && \
	config_path="$${WINMUX_CONFIG_PATH:-}"; \
	if [ -n "$$config_path" ]; then \
	    if [ ! -f "$$config_path" ]; then \
	        echo "Missing WinMux config: $$config_path" >&2; \
	        exit 1; \
	    fi; \
	    exec ./.debug/WinMuxApp --config-path "$$config_path" $(ARGS); \
	else \
	    exec ./.debug/WinMuxApp $(ARGS); \
	fi'

run-clean:
	$(MAKE) build-clean VERSION="$(VERSION)"
	/bin/bash -lc 'cd "$(CURDIR)" && \
	if pgrep -x yabai >/dev/null 2>&1; then echo "warning: yabai is still running and may conflict with WinMux" >&2; fi && \
	if pgrep -x skhd >/dev/null 2>&1; then echo "warning: skhd is still running; its yabai shortcuts will keep firing" >&2; fi && \
	config_path="$${WINMUX_CONFIG_PATH:-}"; \
	if [ -n "$$config_path" ]; then \
	    if [ ! -f "$$config_path" ]; then \
	        echo "Missing WinMux config: $$config_path" >&2; \
	        exit 1; \
	    fi; \
	    exec ./.debug/WinMuxApp --config-path "$$config_path" $(ARGS); \
	else \
	    exec ./.debug/WinMuxApp $(ARGS); \
	fi'

cli:
	$(MAKE) build VERSION="$(VERSION)"
	/bin/bash -lc 'cd "$(CURDIR)" && exec ./.debug/winmux $(ARGS)'

e2e-preflight:
	/bin/bash -lc 'cd "$(CURDIR)" && ./script/e2e/tart-recording-harness preflight'

e2e-smoke:
	/bin/bash -lc 'cd "$(CURDIR)" && ./script/e2e/tart-recording-harness smoke'

e2e-guest-smoke:
	/bin/bash -lc 'cd "$(CURDIR)" && WINMUX_E2E_REQUIRE_GUEST_CONTROL=1 WINMUX_E2E_CAPTURE_MODE=guest ./script/e2e/tart-recording-harness smoke'

e2e-pre-tart-checks:
	/bin/bash -lc 'set -euo pipefail; cd "$(CURDIR)"; \
	if [ -n "$${WINMUX_E2E_PRE_TART_LOG_PATH:-}" ]; then \
		mkdir -p "$$(dirname "$${WINMUX_E2E_PRE_TART_LOG_PATH}")"; \
		exec > >(/usr/bin/tee "$${WINMUX_E2E_PRE_TART_LOG_PATH}") 2>&1; \
	fi; \
	guest_scripts=(script/e2e/guest/*.sh) && \
	bash -n script/e2e/tart-recording-harness && \
	bash -n script/e2e/annotate-recording && \
	bash -n script/e2e/package-root-demo && \
	bash -n script/e2e/verify-root-demo && \
	bash -n script/e2e/write-review-packet && \
	bash -n script/e2e/verify-artifact && \
	bash -n "$${guest_scripts[@]}" && \
	python3 ./script/check-command-metadata && \
	if command -v shellcheck >/dev/null 2>&1; then shellcheck script/e2e/tart-recording-harness script/e2e/annotate-recording script/e2e/package-root-demo script/e2e/verify-root-demo script/e2e/write-review-packet script/e2e/verify-artifact "$${guest_scripts[@]}"; else echo "warning: shellcheck not installed; skipping shell lint" >&2; fi && \
	./script/e2e/package-root-demo --self-test && \
	./script/e2e/verify-artifact --self-test && \
	./script/e2e/tart-recording-harness annotation-preflight && \
	./script/e2e/tart-recording-harness warmup-policy-self-test && \
	swift test --filter '"'"'ConfigBootstrapTest.testStarterConfigParses|ConfigTest.testParseColumnZones|ConfigTest.testParseDefaultConfig|ConfigTest.testParseZoneModeBindingsE2EConfig|ConfigTest.testParseZoneNodeBindingsE2EConfig|ConfigTest.testParseZoneAffinitiesE2EConfig|ConfigTest.testParseNamedZoneLayoutPreset|ConfigTest.testParseZoneSceneWorkspaceBindings|ConfigTest.testParseZoneBindings|ConfigTest.testParseZoneAvailabilitySets|ConfigTest.testParseZoneAffinities|ConfigTest.testParseZoneAffinitiesRequiresZone|ConfigTest.testParseZoneAffinitiesRejectsUnknownNamedZone|ConfigTest.testParseMouseZoneSnapConfig|ConfigTest.testMouseZoneSnapDefaultsForConciseConfig|ConfigTest.testParseZoneSnapPolicySwitchingE2EConfig|ConfigTest.testRejectInvalidMouseZoneSnapConfig|ConfigTest.testRejectInvalidZones|ConfigTest.testRejectInvalidZoneBindings|ConfigTest.testRejectInvalidZoneLayoutPresetReferences|ConfigTest.testRejectInvalidZoneSceneReferences|ConfigTest.testRejectInvalidZoneAvailabilitySets|ConfigTest.testRejectMissingZoneFields|ConfigTest.testRejectInvalidZoneIdsAndWidths|ConfigTest.testRejectDuplicateZoneMonitorSelectors|ConfigTest/testParseOnWindowDetectedZoneRouting|ListMonitorsTest|MonitorTopologyTest|WindowZoneSnapPolicyTest|ZoneCommandTest|WorkspaceSidebarDragTest/testMonitorScopesDedupeZoneViewportsByPhysicalMonitor|WorkspaceSidebarDragTest/testWorkspaceSidebarBuildsZoneTargetsForPhysicalMonitorScope|WorkspaceSidebarDragTest/testSidebarZoneTargetsResolveWithinPhysicalMonitorScopeWhenZoneIdsRepeat|WorkspaceSidebarDragTest/testSameZoneSidebarDropTargetIsNotActionable|WorkspaceSidebarDragTest/testDifferentZoneSidebarDropTargetIsActionable|WorkspaceSidebarDragTest/testMoveWindowFromSidebarToZoneMovesToZoneActiveWorkspace|WorkspaceSidebarDragTest/testMoveTabGroupFromSidebarToZoneMovesWholeGroup'"'"''

e2e-run-product-slice:
	/bin/bash -lc 'set -euo pipefail; cd "$(CURDIR)"; \
	test -n "$(SLICE)"; \
	test -n "$(ACTION)"; \
	test -n "$(RECORD_SECONDS)"; \
	artifact_root="$${WINMUX_E2E_ARTIFACT_ROOT:-$(CURDIR)/artifacts/e2e}"; \
	run_id="$${WINMUX_E2E_RUN_ID:-$(SLICE)-$$(date -u +%Y%m%dT%H%M%SZ)}"; \
	run_dir="$${WINMUX_E2E_RUN_DIR:-$${artifact_root}/$${run_id}}"; \
	mkdir -p "$${run_dir}/logs"; \
	WINMUX_E2E_RUN_ID="$${run_id}" \
	WINMUX_E2E_RUN_DIR="$${run_dir}" \
	WINMUX_E2E_PRE_TART_LOG_PATH="$${run_dir}/logs/pre-tart-checks.log" \
		make e2e-pre-tart-checks; \
	WINMUX_E2E_RUN_ID="$${run_id}" \
	WINMUX_E2E_RUN_DIR="$${run_dir}" \
	WINMUX_E2E_SLICE="$(SLICE)" \
	WINMUX_E2E_REQUIRE_GUEST_CONTROL=1 \
	WINMUX_E2E_CAPTURE_MODE=guest \
	WINMUX_E2E_RECORD_SECONDS="$(RECORD_SECONDS)" \
		./script/e2e/tart-recording-harness "$(ACTION)"'

e2e-verify-slice:
	/bin/bash -lc 'cd "$(CURDIR)" && test -n "$(RUN_DIR)" && ./script/e2e/verify-artifact $(ARGS) "$(RUN_DIR)"'

e2e-verify-slice-check:
	/bin/bash -lc 'cd "$(CURDIR)" && test -n "$(RUN_DIR)" && ./script/e2e/verify-artifact --check-only $(ARGS) "$(RUN_DIR)"'

e2e-slice-closeout-check:
	/bin/bash -lc 'cd "$(CURDIR)" && \
	test -n "$(RUN_DIR)" && \
	./script/e2e/verify-artifact --check-only --require-review --check-sibling-artifacts "$(RUN_DIR)" && \
	require_retrospection() { \
		name="$$1"; \
		if test -s "$(RUN_DIR)/retrospectives/$$name.md" || test -s "$(RUN_DIR)/reviews/retrospection-$$name.md"; then \
			return 0; \
		fi; \
		echo "missing retrospection report: $(RUN_DIR)/retrospectives/$$name.md or $(RUN_DIR)/reviews/retrospection-$$name.md" >&2; \
		return 1; \
	}; \
	require_retrospection process-plan && \
	require_retrospection code-harness && \
	require_retrospection artifact-product'

e2e-verify-root-demo-check:
	/bin/bash -lc 'cd "$(CURDIR)" && test -n "$(RUN_DIR)" && ./script/e2e/verify-root-demo $(ARGS) "$(RUN_DIR)"'

e2e-package-root-demo:
	/bin/bash -lc 'cd "$(CURDIR)" && ./script/e2e/package-root-demo $(ARGS)'

e2e-slice-1:
	$(MAKE) e2e-run-product-slice SLICE=slice-1 ACTION=slice-1 RECORD_SECONDS=18

e2e-slice-2:
	$(MAKE) e2e-run-product-slice SLICE=slice-2 ACTION=slice-2 RECORD_SECONDS=28

e2e-slice-3:
	$(MAKE) e2e-run-product-slice SLICE=slice-3 ACTION=slice-3 RECORD_SECONDS=36

e2e-slice-4:
	$(MAKE) e2e-run-product-slice SLICE=slice-4 ACTION=slice-4 RECORD_SECONDS=44

e2e-slice-5:
	$(MAKE) e2e-run-product-slice SLICE=slice-5 ACTION=slice-5 RECORD_SECONDS=60

e2e-slice-6:
	$(MAKE) e2e-run-product-slice SLICE=slice-6 ACTION=slice-6 RECORD_SECONDS=36

e2e-slice-6b:
	$(MAKE) e2e-run-product-slice SLICE=slice-6b ACTION=slice-6b RECORD_SECONDS=42

e2e-slice-8:
	$(MAKE) e2e-run-product-slice SLICE=slice-8 ACTION=slice-8 RECORD_SECONDS=44

e2e-slice-10:
	$(MAKE) e2e-run-product-slice SLICE=slice-10 ACTION=slice-10 RECORD_SECONDS=54

e2e-slice-11a:
	$(MAKE) e2e-run-product-slice SLICE=slice-11a ACTION=slice-11a RECORD_SECONDS=54

e2e-slice-11b:
	$(MAKE) e2e-run-product-slice SLICE=slice-11b ACTION=slice-11b RECORD_SECONDS=44

e2e-slice-11c:
	$(MAKE) e2e-run-product-slice SLICE=slice-11c ACTION=slice-11c RECORD_SECONDS=64

e2e-slice-12:
	$(MAKE) e2e-run-product-slice SLICE=slice-12 ACTION=slice-12 RECORD_SECONDS=72

e2e-slice-13:
	$(MAKE) e2e-run-product-slice SLICE=slice-13 ACTION=slice-13 RECORD_SECONDS=90

e2e-slice-14:
	$(MAKE) e2e-run-product-slice SLICE=slice-14 ACTION=slice-14 RECORD_SECONDS=46

e2e-slice-15:
	$(MAKE) e2e-run-product-slice SLICE=slice-15 ACTION=slice-15 RECORD_SECONDS=56

e2e-slice-16:
	$(MAKE) e2e-run-product-slice SLICE=slice-16 ACTION=slice-16 RECORD_SECONDS=72

e2e-slice-17:
	$(MAKE) e2e-run-product-slice SLICE=slice-17 ACTION=slice-17 RECORD_SECONDS=70

e2e-slice-18:
	$(MAKE) e2e-run-product-slice SLICE=slice-18 ACTION=slice-18 RECORD_SECONDS=50

e2e-slice-19:
	$(MAKE) e2e-run-product-slice SLICE=slice-19 ACTION=slice-19 RECORD_SECONDS=60

e2e-slice-20:
	$(MAKE) e2e-run-product-slice SLICE=slice-20 ACTION=slice-20 RECORD_SECONDS=90

release:
	$(MAKE) xcodeproj VERSION="$(VERSION)" CODESIGN_IDENTITY="$(CODESIGN_IDENTITY)"
	/bin/bash -lc 'cd "$(CURDIR)" && \
	set -euo pipefail && \
	source ./script/setup.sh && \
	test -n "$(VERSION)" && \
	app_name="WinMux"; \
	release_dir="$(RELEASE_DIR)"; \
	archive_path="$$release_dir/$$app_name-$(VERSION).xcarchive"; \
	derived_data_path="$$release_dir/$$app_name-$(VERSION).deriveddata"; \
	app_path="$$archive_path/Products/Applications/$$app_name.app"; \
	zip_path="$$release_dir/$$app_name-$(VERSION).zip"; \
	log_path="$$release_dir/$$app_name-$(VERSION)-xcodebuild.log"; \
	rm -rf "$$archive_path" "$$zip_path" "$$derived_data_path"; \
	mkdir -p "$$release_dir"; \
	xcodebuild-pretty "$$log_path" \
	    -project WinMux.xcodeproj \
	    -scheme WinMux \
	    -configuration Release \
	    -archivePath "$$archive_path" \
	    -derivedDataPath "$$derived_data_path" \
	    CODE_SIGN_IDENTITY="$(CODESIGN_IDENTITY)" \
	    DEVELOPMENT_TEAM="$(DEVELOPMENT_TEAM)" \
	    CODE_SIGN_STYLE=Automatic \
	    archive; \
	test -d "$$app_path"; \
	codesign --verify --deep --strict --verbose=2 "$$app_path"; \
	codesign -dv --verbose=4 "$$app_path" 2>&1 | grep -F "Authority=$(EXPECTED_CODESIGN_AUTHORITY)" >/dev/null; \
	ditto -c -k --sequesterRsrc --keepParent "$$app_path" "$$zip_path"; \
	if [ "$(PUBLISH)" != "1" ]; then \
	    echo "Skipping GitHub release publish because PUBLISH=$(PUBLISH)"; \
	elif /usr/bin/which gh >/dev/null 2>&1; then \
	    if gh release view "$(RELEASE_TAG)" >/dev/null 2>&1; then \
	        gh release upload "$(RELEASE_TAG)" "$$zip_path" --clobber; \
	    else \
	        if [ "$(RELEASE_NOTES)" = "auto" ]; then \
	            gh release create "$(RELEASE_TAG)" "$$zip_path" --title "$$app_name $(VERSION)" --generate-notes; \
	        else \
	            gh release create "$(RELEASE_TAG)" "$$zip_path" --title "$$app_name $(VERSION)" --notes "$(RELEASE_NOTES)"; \
	        fi; \
	    fi; \
	else \
	    echo "warning: gh is not installed; built $$zip_path but did not publish a GitHub release" >&2; \
	fi'

install:
	$(MAKE) release VERSION="$(VERSION)" CODESIGN_IDENTITY="$(CODESIGN_IDENTITY)" DEVELOPMENT_TEAM="$(DEVELOPMENT_TEAM)" PUBLISH=0
	/bin/bash -lc 'cd "$(CURDIR)" && \
	set -euo pipefail && \
	app_name="WinMux"; \
	release_dir="$(RELEASE_DIR)"; \
	app_path="$$release_dir/$$app_name-$(VERSION).xcarchive/Products/Applications/$$app_name.app"; \
	install_dir="$(APP_INSTALL_DIR)"; \
	install_path="$$install_dir/$$app_name.app"; \
	test -d "$$app_path"; \
	mkdir -p "$$install_dir"; \
	osascript -e "tell application \"$$app_name\" to quit" >/dev/null 2>&1 || true; \
	rm -rf "$$install_path"; \
	ditto "$$app_path" "$$install_path"; \
	xattr -dr com.apple.quarantine "$$install_path" >/dev/null 2>&1 || true; \
	open "$$install_path"'

installed: install

clean:
	/bin/bash -lc 'cd "$(CURDIR)" && rm -rf .build .debug .deps .derived "$(RELEASE_DIR)" WinMux.xcodeproj'
