VERSION ?= 0.0.0-SNAPSHOT
CODESIGN_IDENTITY ?= Apple Development
EXPECTED_CODESIGN_AUTHORITY ?= Apple Development: zxzimeng@gmail.com (4F7GA4MB42)
DEVELOPMENT_TEAM ?= W9C2P3N7Q2
RELEASE_DIR ?= .release
RELEASE_TAG ?= v$(VERSION)
RELEASE_NOTES ?= auto
PUBLISH ?= 1
APP_INSTALL_DIR ?= /Applications
ARGS ?=

.PHONY: generate xcodeproj build build-clean run run-clean cli e2e-preflight e2e-smoke e2e-guest-smoke e2e-pre-tart-checks e2e-run-product-slice e2e-verify-slice e2e-review-lint e2e-verify-slice-check e2e-slice-closeout-check e2e-verify-root-demo-check e2e-root-demo-closeout-check e2e-package-root-demo e2e-support-bundle-schema-check e2e-slice-49-docs-check e2e-slice-50-package-check e2e-slice-1 e2e-slice-2 e2e-slice-3 e2e-slice-4 e2e-slice-5 e2e-slice-6 e2e-slice-6b e2e-slice-8 e2e-slice-10 e2e-slice-11a e2e-slice-11b e2e-slice-11c e2e-slice-12 e2e-slice-13 e2e-slice-14 e2e-slice-15 e2e-slice-16 e2e-slice-17 e2e-slice-18 e2e-slice-19 e2e-slice-20 e2e-slice-21 e2e-slice-22 e2e-slice-23 e2e-slice-24 e2e-slice-25 e2e-slice-26 e2e-slice-27 e2e-slice-28 e2e-slice-29 e2e-slice-31 e2e-slice-32 e2e-slice-33 e2e-slice-34 e2e-slice-35 e2e-slice-37 e2e-slice-38 e2e-slice-39 e2e-slice-40 e2e-slice-41 e2e-slice-42 e2e-slice-43 e2e-slice-44 e2e-slice-45 e2e-slice-46 e2e-slice-47 e2e-slice-48 e2e-slice-50 beta-package release install installed clean

generate:
	/bin/bash -lc 'cd "$(CURDIR)" && \
	printf "%s\n" "// FILE IS GENERATED BY Makefile" "public let winMuxAppVersion = \"$(VERSION)\"" > Sources/Common/versionGenerated.swift && \
	git_hash="$$(git rev-parse HEAD 2>/dev/null || echo SNAPSHOT)"; \
	git_short_hash="$$(git rev-parse --short HEAD 2>/dev/null || echo SNAPSHOT)"; \
	printf "%s\n" "// FILE IS GENERATED BY Makefile" "public let gitHash = \"$$git_hash\"" "public let gitShortHash = \"$$git_short_hash\"" > Sources/Common/gitHashGenerated.swift'

xcodeproj:
	$(MAKE) generate VERSION="$(VERSION)"
	/bin/bash -lc 'cd "$(CURDIR)" && \
	source ./script/setup.sh && \
	export XCODEGEN_WINMUX_VERSION="$(VERSION)" && \
	export XCODEGEN_WINMUX_CODE_SIGN_IDENTITY="$(CODESIGN_IDENTITY)" && \
	export XCODEGEN_WINMUX_DEVELOPMENT_TEAM="$(DEVELOPMENT_TEAM)" && \
	./script/install-dep.sh --xcodegen && \
	./.deps/xcodegen/xcodegen'

build:
	/bin/bash -lc 'cd "$(CURDIR)" && \
	set -euo pipefail && \
	generated_snapshot="$$(mktemp -d)" && \
	cp Sources/Common/gitHashGenerated.swift "$$generated_snapshot/gitHashGenerated.swift" && \
	cp Sources/Common/versionGenerated.swift "$$generated_snapshot/versionGenerated.swift" && \
	restore_generated() { \
	    cp "$$generated_snapshot/gitHashGenerated.swift" Sources/Common/gitHashGenerated.swift; \
	    cp "$$generated_snapshot/versionGenerated.swift" Sources/Common/versionGenerated.swift; \
	    rm -rf "$$generated_snapshot"; \
	}; \
	trap restore_generated EXIT && \
	printf "%s\n" "// FILE IS GENERATED BY Makefile" "public let winMuxAppVersion = \"$(VERSION)\"" > Sources/Common/versionGenerated.swift && \
	git_hash="$$(git rev-parse HEAD 2>/dev/null || echo SNAPSHOT)" && \
	git_short_hash="$$(git rev-parse --short HEAD 2>/dev/null || echo SNAPSHOT)" && \
	printf "%s\n" "// FILE IS GENERATED BY Makefile" "public let gitHash = \"$$git_hash\"" "public let gitShortHash = \"$$git_short_hash\"" > Sources/Common/gitHashGenerated.swift && \
	source ./script/setup.sh && \
	swift build && \
	swift build --target AppBundleTests && \
	rm -rf .debug && \
	mkdir .debug && \
	cp -r .build/debug/winmux .debug && \
	cp -r .build/debug/WinMuxApp .debug'

build-clean:
	/bin/bash -lc 'cd "$(CURDIR)" && rm -rf .build .debug'
	$(MAKE) build VERSION="$(VERSION)"

run:
	$(MAKE) build VERSION="$(VERSION)"
	/bin/bash -lc 'cd "$(CURDIR)" && \
	if pgrep -x yabai >/dev/null 2>&1; then echo "warning: yabai is still running and may conflict with WinMux" >&2; fi && \
	if pgrep -x skhd >/dev/null 2>&1; then echo "warning: skhd is still running; its yabai shortcuts will keep firing" >&2; fi && \
	config_path="$${WINMUX_CONFIG_PATH:-}"; \
	if [ -n "$$config_path" ]; then \
	    if [ ! -f "$$config_path" ]; then \
	        echo "Missing WinMux config: $$config_path" >&2; \
	        exit 1; \
	    fi; \
	    exec ./.debug/WinMuxApp --config-path "$$config_path" $(ARGS); \
	else \
	    exec ./.debug/WinMuxApp $(ARGS); \
	fi'

run-clean:
	$(MAKE) build-clean VERSION="$(VERSION)"
	/bin/bash -lc 'cd "$(CURDIR)" && \
	if pgrep -x yabai >/dev/null 2>&1; then echo "warning: yabai is still running and may conflict with WinMux" >&2; fi && \
	if pgrep -x skhd >/dev/null 2>&1; then echo "warning: skhd is still running; its yabai shortcuts will keep firing" >&2; fi && \
	config_path="$${WINMUX_CONFIG_PATH:-}"; \
	if [ -n "$$config_path" ]; then \
	    if [ ! -f "$$config_path" ]; then \
	        echo "Missing WinMux config: $$config_path" >&2; \
	        exit 1; \
	    fi; \
	    exec ./.debug/WinMuxApp --config-path "$$config_path" $(ARGS); \
	else \
	    exec ./.debug/WinMuxApp $(ARGS); \
	fi'

cli:
	$(MAKE) build VERSION="$(VERSION)"
	/bin/bash -lc 'cd "$(CURDIR)" && exec ./.debug/winmux $(ARGS)'

e2e-preflight:
	/bin/bash -lc 'cd "$(CURDIR)" && ./script/e2e/tart-recording-harness preflight'

e2e-smoke:
	/bin/bash -lc 'cd "$(CURDIR)" && ./script/e2e/tart-recording-harness smoke'

e2e-guest-smoke:
	/bin/bash -lc 'cd "$(CURDIR)" && WINMUX_E2E_REQUIRE_GUEST_CONTROL=1 WINMUX_E2E_CAPTURE_MODE=guest ./script/e2e/tart-recording-harness smoke'

e2e-pre-tart-checks:
	/bin/bash -lc 'set -euo pipefail; cd "$(CURDIR)"; \
	if [ -n "$${WINMUX_E2E_PRE_TART_LOG_PATH:-}" ]; then \
		mkdir -p "$$(dirname "$${WINMUX_E2E_PRE_TART_LOG_PATH}")"; \
		exec > >(/usr/bin/tee "$${WINMUX_E2E_PRE_TART_LOG_PATH}") 2>&1; \
	fi; \
	guest_scripts=(script/e2e/guest/*.sh) && \
	bash -n script/e2e/tart-recording-harness && \
	bash -n script/e2e/annotate-recording && \
	bash -n script/e2e/package-root-demo && \
	bash -n script/e2e/package-slice-50 && \
	bash -n script/e2e/verify-root-demo && \
	bash -n script/e2e/record-reviewer-attempt && \
	bash -n script/e2e/write-visible-proof-excerpt && \
	bash -n script/e2e/root-demo-closeout && \
	bash -n script/e2e/write-review-packet && \
	bash -n script/e2e/check-visible-proof-board && \
	bash -n script/e2e/check-zone-init-local-validation && \
	bash -n script/e2e/check-generated-version-clean && \
	bash -n script/e2e/check-pre-tart-review-gate && \
	bash -n script/e2e/check-slice-46-contract && \
	bash -n script/e2e/check-slice-47-contract && \
	bash -n script/e2e/check-slice-48-contract && \
	bash -n script/e2e/check-support-bundle-schema && \
	bash -n script/e2e/check-slice-49-docs && \
	bash -n script/e2e/check-slice-50-package && \
	bash -n script/e2e/verify-artifact && \
	bash -n "$${guest_scripts[@]}" && \
		echo "[winmux-e2e] bash syntax checks PASS" && \
		python3 ./script/check-command-metadata && \
		git diff --check && \
		echo "[winmux-e2e] git diff --check PASS" && \
	if command -v shellcheck >/dev/null 2>&1; then shellcheck script/e2e/tart-recording-harness script/e2e/annotate-recording script/e2e/package-root-demo script/e2e/package-slice-50 script/e2e/verify-root-demo script/e2e/record-reviewer-attempt script/e2e/write-visible-proof-excerpt script/e2e/root-demo-closeout script/e2e/write-review-packet script/e2e/check-visible-proof-board script/e2e/check-zone-init-local-validation script/e2e/check-generated-version-clean script/e2e/check-pre-tart-review-gate script/e2e/check-slice-46-contract script/e2e/check-slice-47-contract script/e2e/check-slice-48-contract script/e2e/check-support-bundle-schema script/e2e/check-slice-49-docs script/e2e/check-slice-50-package script/e2e/verify-artifact "$${guest_scripts[@]}" && echo "[winmux-e2e] shellcheck PASS"; else echo "warning: shellcheck not installed; skipping shell lint" >&2; fi && \
	./script/e2e/check-generated-version-clean && \
	./script/e2e/check-slice-46-contract && \
	./script/e2e/check-slice-47-contract && \
	./script/e2e/check-slice-48-contract && \
	./script/e2e/check-support-bundle-schema --self-test && \
	./script/e2e/check-support-bundle-schema artifacts/e2e/slice-48-20260702T094800Z/logs/slice-48-zone-support-bundle && \
	swift build --target Cli && \
	./script/e2e/check-slice-49-docs && \
	./script/e2e/record-reviewer-attempt --self-test && \
	./script/e2e/write-visible-proof-excerpt --self-test && \
	./script/e2e/check-visible-proof-board --self-test && \
	./script/e2e/root-demo-closeout --self-test && \
	./script/e2e/package-root-demo --self-test && \
	./script/e2e/verify-artifact --self-test && \
	./script/e2e/check-slice-50-package --self-test && \
	./script/e2e/check-zone-init-local-validation --self-test && \
	./script/e2e/check-pre-tart-review-gate --self-test && \
	./script/e2e/tart-recording-harness abort-status-self-test && \
	./script/e2e/tart-recording-harness pre-tart-gate-self-test && \
	mouse_event_tmp="$$(mktemp -d)" && trap '"'"'rm -rf "$$mouse_event_tmp"'"'"' EXIT && \
	ARTIFACTS_DIR="$$mouse_event_tmp" WINMUX_E2E_RECORDING_TIMING_HELPERS_PHASE=self-test ./script/e2e/guest/recording-timing-helpers.sh && \
	ARTIFACTS_DIR="$$mouse_event_tmp" WINMUX_E2E_ZONE_WINDOW_HELPERS_PHASE=self-test ./script/e2e/guest/zone-window-helpers.sh && \
	REPO_DIR="$(CURDIR)" ARTIFACTS_DIR="$$mouse_event_tmp" WINMUX_E2E_MOUSE_SNAP_PHASE=self-test ./script/e2e/guest/slice-12-mouse-zone-snap.sh && \
	REPO_DIR="$(CURDIR)" ARTIFACTS_DIR="$$mouse_event_tmp" WINMUX_E2E_SLICE26_PHASE=self-test ./script/e2e/guest/slice-26-zone-divider-drag.sh && \
	REPO_DIR="$(CURDIR)" ARTIFACTS_DIR="$$mouse_event_tmp" WINMUX_E2E_SLICE28_PHASE=self-test ./script/e2e/guest/slice-28-export-zone-layout.sh && \
	REPO_DIR="$(CURDIR)" ARTIFACTS_DIR="$$mouse_event_tmp" WINMUX_E2E_SLICE29_PHASE=self-test ./script/e2e/guest/slice-29-save-zone-layout.sh && \
	REPO_DIR="$(CURDIR)" ARTIFACTS_DIR="$$mouse_event_tmp" WINMUX_E2E_SLICE31_PHASE=self-test ./script/e2e/guest/slice-31-relaunch-saved-layout.sh && \
	REPO_DIR="$(CURDIR)" ARTIFACTS_DIR="$$mouse_event_tmp" WINMUX_E2E_SLICE32_PHASE=self-test /bin/bash ./script/e2e/guest/slice-32-divider-save-relaunch.sh && \
	REPO_DIR="$(CURDIR)" ARTIFACTS_DIR="$$mouse_event_tmp" WINMUX_E2E_SLICE35_PHASE=self-test /bin/bash ./script/e2e/guest/slice-35-starter-ultrawide-template.sh && \
	REPO_DIR="$(CURDIR)" ARTIFACTS_DIR="$$mouse_event_tmp" WINMUX_E2E_SLICE37_PHASE=self-test /bin/bash ./script/e2e/guest/slice-37-starter-onboarding.sh && \
	REPO_DIR="$(CURDIR)" ARTIFACTS_DIR="$$mouse_event_tmp" WINMUX_E2E_SLICE38_PHASE=self-test /bin/bash ./script/e2e/guest/slice-38-user-readiness.sh && \
	REPO_DIR="$(CURDIR)" ARTIFACTS_DIR="$$mouse_event_tmp" WINMUX_E2E_SLICE39_PHASE=self-test /bin/bash ./script/e2e/guest/slice-39-dogfood-install-permissions.sh && \
	echo "[winmux-e2e] Slice 40 guest self-test START: script/e2e/guest/slice-40-zone-setup-assistant.sh" && \
	REPO_DIR="$(CURDIR)" ARTIFACTS_DIR="$$mouse_event_tmp" WINMUX_E2E_SLICE40_PHASE=self-test /bin/bash ./script/e2e/guest/slice-40-zone-setup-assistant.sh && \
	echo "[winmux-e2e] Slice 40 guest self-test PASS: script/e2e/guest/slice-40-zone-setup-assistant.sh" && \
	echo "[winmux-e2e] Slice 41 guest self-test START: script/e2e/guest/slice-41-zone-affinity-beta.sh" && \
	REPO_DIR="$(CURDIR)" ARTIFACTS_DIR="$$mouse_event_tmp" WINMUX_E2E_SLICE41_PHASE=self-test /bin/bash ./script/e2e/guest/slice-41-zone-affinity-beta.sh && \
	echo "[winmux-e2e] Slice 41 guest self-test PASS: script/e2e/guest/slice-41-zone-affinity-beta.sh" && \
	echo "[winmux-e2e] Slice 42 guest self-test START: script/e2e/guest/slice-42-zone-availability-profiles.sh" && \
	REPO_DIR="$(CURDIR)" ARTIFACTS_DIR="$$mouse_event_tmp" WINMUX_E2E_SLICE42_PHASE=self-test /bin/bash ./script/e2e/guest/slice-42-zone-availability-profiles.sh && \
	echo "[winmux-e2e] Slice 42 guest self-test PASS: script/e2e/guest/slice-42-zone-availability-profiles.sh" && \
	echo "[winmux-e2e] Slice 45 guest self-test START: script/e2e/guest/slice-45-display-topology-recovery.sh" && \
	REPO_DIR="$(CURDIR)" ARTIFACTS_DIR="$$mouse_event_tmp" WINMUX_E2E_SLICE45_PHASE=self-test /bin/bash ./script/e2e/guest/slice-45-display-topology-recovery.sh && \
	echo "[winmux-e2e] Slice 45 guest self-test PASS: script/e2e/guest/slice-45-display-topology-recovery.sh" && \
	echo "[winmux-e2e] Slice 46 guest self-test START: script/e2e/guest/slice-46-persistence-rollback-doctor.sh" && \
	REPO_DIR="$(CURDIR)" ARTIFACTS_DIR="$$mouse_event_tmp" WINMUX_E2E_SLICE46_PHASE=self-test /bin/bash ./script/e2e/guest/slice-46-persistence-rollback-doctor.sh && \
	echo "[winmux-e2e] Slice 46 guest self-test PASS: script/e2e/guest/slice-46-persistence-rollback-doctor.sh" && \
	echo "[winmux-e2e] Slice 47 guest self-test START: script/e2e/guest/slice-47-zone-chrome-polish.sh" && \
	REPO_DIR="$(CURDIR)" ARTIFACTS_DIR="$$mouse_event_tmp" WINMUX_E2E_SLICE47_PHASE=self-test /bin/bash ./script/e2e/guest/slice-47-zone-chrome-polish.sh && \
	echo "[winmux-e2e] Slice 47 guest self-test PASS: script/e2e/guest/slice-47-zone-chrome-polish.sh" && \
	echo "[winmux-e2e] Slice 48 guest self-test START: script/e2e/guest/slice-48-support-bundle-diagnostics.sh" && \
	REPO_DIR="$(CURDIR)" ARTIFACTS_DIR="$$mouse_event_tmp" WINMUX_E2E_SLICE48_PHASE=self-test /bin/bash ./script/e2e/guest/slice-48-support-bundle-diagnostics.sh && \
	echo "[winmux-e2e] Slice 48 guest self-test PASS: script/e2e/guest/slice-48-support-bundle-diagnostics.sh" && \
	echo "[winmux-e2e] Slice 50 guest self-test START: script/e2e/guest/slice-50-package-release.sh" && \
	REPO_DIR="$(CURDIR)" ARTIFACTS_DIR="$$mouse_event_tmp" WINMUX_E2E_SLICE50_PHASE=self-test /bin/bash ./script/e2e/guest/slice-50-package-release.sh && \
	echo "[winmux-e2e] Slice 50 guest self-test PASS: script/e2e/guest/slice-50-package-release.sh" && \
	./script/e2e/tart-recording-harness annotation-preflight && \
	./script/e2e/tart-recording-harness warmup-policy-self-test && \
	swift test --filter '"'"'AppBundleUtilTest|DoctorCommandTest|FocusCommandTest/testFocusedMonitorChangedHookFiresAcrossZonesOnSamePhysicalMonitor|ConfigBootstrapTest|ConfigTest.testParseColumnZones|ConfigTest.testParseDefaultConfig|ConfigTest.testRenderConfigDoctorLinesForValidZonesConfig|ConfigTest.testRenderConfigDoctorLinesForInvalidZonesConfig|ConfigTest.testRenderConfigDoctorLinesIncludesRuntimeOverlayState|ConfigTest.testParseZoneModeBindingsE2EConfig|ConfigTest.testParseZoneModeV2E2EConfig|ConfigTest.testParseZoneSaveLayoutE2EConfig|ConfigTest.testParseZoneRelaunchSavedLayoutE2EConfig|ConfigTest.testParseZoneNodeBindingsE2EConfig|ConfigTest.testParseZoneAffinitiesE2EConfig|ConfigTest.testParseZoneAffinitiesBetaE2EConfig|ConfigTest.testParseZoneAvailabilityProfilesE2EConfig|ConfigTest.testParseZoneChromePolishE2EConfig|ConfigTest.testParseNamedZoneLayoutPreset|ConfigTest.testParseZoneSceneWorkspaceBindings|ConfigTest.testParseZoneBindings|ConfigTest.testParseZoneAvailabilitySets|ConfigTest.testParseZoneAffinities|ConfigTest.testParseZoneAffinitiesRequiresZone|ConfigTest.testParseZoneAffinitiesRejectsUnknownNamedZone|ConfigTest.testParseMouseZoneSnapConfig|ConfigTest.testMouseZoneSnapDefaultsForConciseConfig|ConfigTest.testParseZoneSnapPolicySwitchingE2EConfig|ConfigTest.testParseFloatUnlessSnapE2EConfig|ConfigTest.testParseFloatUnlessSnapSecondaryButtonE2EConfig|ConfigTest.testParseMouseGestureConfigurabilityE2EConfig|ConfigTest.testParseDragOverlaySemanticsE2EConfig|ConfigTest.testParseWindowSlotSnapE2EConfig|ConfigTest.testRejectInvalidMouseZoneSnapConfig|ConfigTest.testRejectInvalidZones|ConfigTest.testRejectInvalidZoneBindings|ConfigTest.testRejectInvalidZoneLayoutPresetReferences|ConfigTest.testRejectInvalidZoneSceneReferences|ConfigTest.testRejectInvalidZoneAvailabilitySets|ConfigTest.testRejectMissingZoneFields|ConfigTest.testRejectInvalidZoneIdsAndWidths|ConfigTest.testRejectDuplicateZoneMonitorSelectors|ConfigTest/testParseOnWindowDetectedZoneRouting|ListWindowsTest|ListMonitorsTest|MonitorTopologyTest|WindowZoneSnapPolicyTest|ZoneCommandTest|WorkspaceSidebarDragTest/testMonitorScopesDedupeZoneViewportsByPhysicalMonitor|WorkspaceSidebarDragTest/testWorkspaceSidebarBuildsZoneTargetsForPhysicalMonitorScope|WorkspaceSidebarDragTest/testSidebarZoneTargetsResolveWithinPhysicalMonitorScopeWhenZoneIdsRepeat|WorkspaceSidebarDragTest/testWorkspaceSidebarKeepsDisabledZoneTargetsReadable|WorkspaceSidebarDragTest/testSameZoneSidebarDropTargetIsNotActionable|WorkspaceSidebarDragTest/testDifferentZoneSidebarDropTargetIsActionable|WorkspaceSidebarDragTest/testMoveWindowFromSidebarToZoneMovesToZoneActiveWorkspace|WorkspaceSidebarDragTest/testMoveTabGroupFromSidebarToZoneMovesWholeGroup'"'"' && \
	./script/e2e/check-generated-version-clean'

e2e-run-product-slice:
	/bin/bash -lc 'set -euo pipefail; cd "$(CURDIR)"; \
	test -n "$(SLICE)"; \
	test -n "$(ACTION)"; \
	test -n "$(RECORD_SECONDS)"; \
	artifact_root="$${WINMUX_E2E_ARTIFACT_ROOT:-$(CURDIR)/artifacts/e2e}"; \
	run_id="$${WINMUX_E2E_RUN_ID:-$(SLICE)-$$(date -u +%Y%m%dT%H%M%SZ)}"; \
	run_dir="$${WINMUX_E2E_RUN_DIR:-$${artifact_root}/$${run_id}}"; \
	mkdir -p "$${run_dir}/logs"; \
	if [ "$(REQUIRE_PRE_TART_REVIEW)" = "1" ] && [ -s "$${run_dir}/reviews/pre-tart/freshness.env" ]; then \
		./script/e2e/check-pre-tart-review-gate "$${run_dir}" "$(SLICE)"; \
	else \
		WINMUX_E2E_RUN_ID="$${run_id}" \
		WINMUX_E2E_RUN_DIR="$${run_dir}" \
			WINMUX_E2E_PRE_TART_LOG_PATH="$${run_dir}/logs/pre-tart-checks.log" \
				make e2e-pre-tart-checks; \
		if [ "$(REQUIRE_PRE_TART_REVIEW)" = "1" ]; then \
			./script/e2e/check-pre-tart-review-gate --write-freshness "$${run_dir}" "$(SLICE)"; \
			./script/e2e/check-pre-tart-review-gate "$${run_dir}" "$(SLICE)"; \
		fi; \
	fi; \
	WINMUX_E2E_RUN_ID="$${run_id}" \
	WINMUX_E2E_RUN_DIR="$${run_dir}" \
	WINMUX_E2E_SLICE="$(SLICE)" \
	WINMUX_E2E_REQUIRE_GUEST_CONTROL=1 \
	WINMUX_E2E_CAPTURE_MODE=guest \
	WINMUX_E2E_RECORD_SECONDS="$(RECORD_SECONDS)" \
		./script/e2e/tart-recording-harness "$(ACTION)"'

e2e-verify-slice:
	/bin/bash -lc 'set -euo pipefail; cd "$(CURDIR)" && \
	test -n "$(RUN_DIR)" && \
	run_name="$$(basename "$(RUN_DIR)")"; \
	if test -s "$(RUN_DIR)/logs/package-slice-manifest.txt" && grep -Fx "kind=package" "$(RUN_DIR)/logs/package-slice-manifest.txt" >/dev/null; then \
	    ./script/e2e/check-slice-50-package $(ARGS) "$(RUN_DIR)"; \
	elif case "$$run_name" in slice-50*) true ;; *) false ;; esac; then \
	    ./script/e2e/check-slice-50-package $(ARGS) "$(RUN_DIR)"; \
	elif test -s "$(RUN_DIR)/logs/package-provenance.env"; then \
	    ./script/e2e/check-slice-50-package $(ARGS) "$(RUN_DIR)"; \
	else \
	    ./script/e2e/verify-artifact $(ARGS) "$(RUN_DIR)"; \
	fi'

e2e-review-lint:
	/bin/bash -lc 'set -euo pipefail; cd "$(CURDIR)" && \
	test -n "$(RUN_DIR)" && \
	if test -s "$(RUN_DIR)/logs/docs-slice-manifest.txt" && grep -Fx "kind=docs" "$(RUN_DIR)/logs/docs-slice-manifest.txt" >/dev/null; then \
	    ./script/e2e/check-slice-49-docs --require-review "$(RUN_DIR)"; \
	elif test -s "$(RUN_DIR)/logs/package-slice-manifest.txt" && grep -Fx "kind=package" "$(RUN_DIR)/logs/package-slice-manifest.txt" >/dev/null; then \
	    ./script/e2e/check-slice-50-package --require-review "$(RUN_DIR)"; \
	elif case "$$(basename "$(RUN_DIR)")" in slice-50*) true ;; *) false ;; esac; then \
	    ./script/e2e/check-slice-50-package --require-review "$(RUN_DIR)"; \
	elif test -s "$(RUN_DIR)/logs/package-provenance.env"; then \
	    ./script/e2e/check-slice-50-package --require-review "$(RUN_DIR)"; \
	else \
	    ./script/e2e/verify-artifact --review-lint "$(RUN_DIR)"; \
	fi'

e2e-verify-slice-check:
	/bin/bash -lc 'set -euo pipefail; cd "$(CURDIR)" && \
	test -n "$(RUN_DIR)" && \
	run_name="$$(basename "$(RUN_DIR)")"; \
	if test -s "$(RUN_DIR)/logs/package-slice-manifest.txt" && grep -Fx "kind=package" "$(RUN_DIR)/logs/package-slice-manifest.txt" >/dev/null; then \
	    ./script/e2e/check-slice-50-package $(ARGS) "$(RUN_DIR)"; \
	elif case "$$run_name" in slice-50*) true ;; *) false ;; esac; then \
	    ./script/e2e/check-slice-50-package $(ARGS) "$(RUN_DIR)"; \
	elif test -s "$(RUN_DIR)/logs/package-provenance.env"; then \
	    ./script/e2e/check-slice-50-package $(ARGS) "$(RUN_DIR)"; \
	else \
	    ./script/e2e/verify-artifact --check-only $(ARGS) "$(RUN_DIR)"; \
	fi'

e2e-slice-closeout-check:
	/bin/bash -lc 'set -euo pipefail; cd "$(CURDIR)" && \
	test -n "$(RUN_DIR)" && \
	if test -s "$(RUN_DIR)/logs/docs-slice-manifest.txt" && grep -Fx "kind=docs" "$(RUN_DIR)/logs/docs-slice-manifest.txt" >/dev/null; then \
	    ./script/e2e/check-slice-49-docs --closeout "$(RUN_DIR)"; \
	    echo "[winmux-e2e] docs slice closeout PASS: $(RUN_DIR)"; \
	    exit 0; \
	fi; \
	if test -s "$(RUN_DIR)/logs/package-slice-manifest.txt" && grep -Fx "kind=package" "$(RUN_DIR)/logs/package-slice-manifest.txt" >/dev/null; then \
	    ./script/e2e/check-slice-50-package --closeout "$(RUN_DIR)"; \
	    echo "[winmux-e2e] package slice closeout PASS: $(RUN_DIR)"; \
	    exit 0; \
	fi; \
	if case "$$(basename "$(RUN_DIR)")" in slice-50*) true ;; *) false ;; esac; then \
	    ./script/e2e/check-slice-50-package --closeout "$(RUN_DIR)"; \
	    echo "[winmux-e2e] package slice closeout PASS: $(RUN_DIR)"; \
	    exit 0; \
	fi; \
	if test -s "$(RUN_DIR)/logs/package-provenance.env"; then \
	    ./script/e2e/check-slice-50-package --closeout "$(RUN_DIR)"; \
	    echo "[winmux-e2e] package slice closeout PASS: $(RUN_DIR)"; \
	    exit 0; \
	fi; \
	require_retrospection() { \
		name="$$1"; \
		if test -s "$(RUN_DIR)/retrospectives/$$name.md" || test -s "$(RUN_DIR)/reviews/retrospection-$$name.md"; then \
			return 0; \
		fi; \
		echo "missing retrospection report: $(RUN_DIR)/retrospectives/$$name.md or $(RUN_DIR)/reviews/retrospection-$$name.md" >&2; \
		return 1; \
	}; \
	require_log() { \
		path="$$1"; \
		if test -s "$(RUN_DIR)/logs/$$path"; then \
			return 0; \
		fi; \
		echo "missing closeout gate log: $(RUN_DIR)/logs/$$path" >&2; \
		return 1; \
	}; \
	./script/e2e/verify-artifact --check-only --require-review --check-sibling-artifacts "$(RUN_DIR)" && \
	./script/e2e/check-generated-version-clean && \
	require_log review-lint.log && \
	require_log post-review-verify.log && \
	require_retrospection process-plan && \
	require_retrospection code-harness && \
	require_retrospection artifact-product && \
	echo "[winmux-e2e] slice closeout PASS: $(RUN_DIR)"'

e2e-verify-root-demo-check:
	/bin/bash -lc 'cd "$(CURDIR)" && test -n "$(RUN_DIR)" && ./script/e2e/verify-root-demo $(ARGS) "$(RUN_DIR)"'

e2e-root-demo-closeout-check:
	/bin/bash -lc 'cd "$(CURDIR)" && test -n "$(RUN_DIR)" && ./script/e2e/root-demo-closeout $(ARGS) "$(RUN_DIR)"'

e2e-package-root-demo:
	/bin/bash -lc 'cd "$(CURDIR)" && ./script/e2e/package-root-demo $(ARGS)'

e2e-support-bundle-schema-check:
	/bin/bash -lc 'cd "$(CURDIR)" && test -n "$(BUNDLE_DIR)" && ./script/e2e/check-support-bundle-schema $(ARGS) "$(BUNDLE_DIR)"'

e2e-slice-49-docs-check:
	/bin/bash -lc 'cd "$(CURDIR)" && if test -n "$(RUN_DIR)"; then ./script/e2e/check-slice-49-docs $(ARGS) "$(RUN_DIR)"; else ./script/e2e/check-slice-49-docs $(ARGS); fi'

e2e-slice-50-package-check:
	/bin/bash -lc 'cd "$(CURDIR)" && test -n "$(RUN_DIR)" && ./script/e2e/check-slice-50-package $(ARGS) "$(RUN_DIR)"'

e2e-slice-1:
	$(MAKE) e2e-run-product-slice SLICE=slice-1 ACTION=slice-1 RECORD_SECONDS=18

e2e-slice-2:
	$(MAKE) e2e-run-product-slice SLICE=slice-2 ACTION=slice-2 RECORD_SECONDS=28

e2e-slice-3:
	$(MAKE) e2e-run-product-slice SLICE=slice-3 ACTION=slice-3 RECORD_SECONDS=36

e2e-slice-4:
	$(MAKE) e2e-run-product-slice SLICE=slice-4 ACTION=slice-4 RECORD_SECONDS=44

e2e-slice-5:
	$(MAKE) e2e-run-product-slice SLICE=slice-5 ACTION=slice-5 RECORD_SECONDS=60

e2e-slice-6:
	$(MAKE) e2e-run-product-slice SLICE=slice-6 ACTION=slice-6 RECORD_SECONDS=36

e2e-slice-6b:
	$(MAKE) e2e-run-product-slice SLICE=slice-6b ACTION=slice-6b RECORD_SECONDS=42

e2e-slice-8:
	$(MAKE) e2e-run-product-slice SLICE=slice-8 ACTION=slice-8 RECORD_SECONDS=44

e2e-slice-10:
	$(MAKE) e2e-run-product-slice SLICE=slice-10 ACTION=slice-10 RECORD_SECONDS=54

e2e-slice-11a:
	$(MAKE) e2e-run-product-slice SLICE=slice-11a ACTION=slice-11a RECORD_SECONDS=54

e2e-slice-11b:
	$(MAKE) e2e-run-product-slice SLICE=slice-11b ACTION=slice-11b RECORD_SECONDS=44

e2e-slice-11c:
	$(MAKE) e2e-run-product-slice SLICE=slice-11c ACTION=slice-11c RECORD_SECONDS=64

e2e-slice-12:
	$(MAKE) e2e-run-product-slice SLICE=slice-12 ACTION=slice-12 RECORD_SECONDS=72

e2e-slice-13:
	$(MAKE) e2e-run-product-slice SLICE=slice-13 ACTION=slice-13 RECORD_SECONDS=90

e2e-slice-14:
	$(MAKE) e2e-run-product-slice SLICE=slice-14 ACTION=slice-14 RECORD_SECONDS=46

e2e-slice-15:
	$(MAKE) e2e-run-product-slice SLICE=slice-15 ACTION=slice-15 RECORD_SECONDS=56

e2e-slice-16:
	$(MAKE) e2e-run-product-slice SLICE=slice-16 ACTION=slice-16 RECORD_SECONDS=72

e2e-slice-17:
	$(MAKE) e2e-run-product-slice SLICE=slice-17 ACTION=slice-17 RECORD_SECONDS=70

e2e-slice-18:
	$(MAKE) e2e-run-product-slice SLICE=slice-18 ACTION=slice-18 RECORD_SECONDS=50

e2e-slice-19:
	$(MAKE) e2e-run-product-slice SLICE=slice-19 ACTION=slice-19 RECORD_SECONDS=60

e2e-slice-20:
	$(MAKE) e2e-run-product-slice SLICE=slice-20 ACTION=slice-20 RECORD_SECONDS=90

e2e-slice-21:
	$(MAKE) e2e-run-product-slice SLICE=slice-21 ACTION=slice-21 RECORD_SECONDS=92

e2e-slice-22:
	$(MAKE) e2e-run-product-slice SLICE=slice-22 ACTION=slice-22 RECORD_SECONDS=86

e2e-slice-23:
	$(MAKE) e2e-run-product-slice SLICE=slice-23 ACTION=slice-23 RECORD_SECONDS=86

e2e-slice-24:
	$(MAKE) e2e-run-product-slice SLICE=slice-24 ACTION=slice-24 RECORD_SECONDS=86

e2e-slice-25:
	$(MAKE) e2e-run-product-slice SLICE=slice-25 ACTION=slice-25 RECORD_SECONDS=86

e2e-slice-26:
	$(MAKE) e2e-run-product-slice SLICE=slice-26 ACTION=slice-26 RECORD_SECONDS=80

e2e-slice-27:
	$(MAKE) e2e-run-product-slice SLICE=slice-27 ACTION=slice-27 RECORD_SECONDS=86

e2e-slice-28:
	$(MAKE) e2e-run-product-slice SLICE=slice-28 ACTION=slice-28 RECORD_SECONDS=68

e2e-slice-29:
	$(MAKE) e2e-run-product-slice SLICE=slice-29 ACTION=slice-29 RECORD_SECONDS=74

e2e-slice-31:
	$(MAKE) e2e-run-product-slice SLICE=slice-31 ACTION=slice-31 RECORD_SECONDS=78

e2e-slice-32:
	$(MAKE) e2e-run-product-slice SLICE=slice-32 ACTION=slice-32 RECORD_SECONDS=104

e2e-slice-33:
	$(MAKE) e2e-run-product-slice SLICE=slice-33 ACTION=slice-33 RECORD_SECONDS=72

e2e-slice-34:
	$(MAKE) e2e-run-product-slice SLICE=slice-34 ACTION=slice-34 RECORD_SECONDS=72 REQUIRE_PRE_TART_REVIEW=1

e2e-slice-35:
	$(MAKE) e2e-run-product-slice SLICE=slice-35 ACTION=slice-35 RECORD_SECONDS=60 REQUIRE_PRE_TART_REVIEW=1

e2e-slice-37:
	$(MAKE) e2e-run-product-slice SLICE=slice-37 ACTION=slice-37 RECORD_SECONDS=72 REQUIRE_PRE_TART_REVIEW=1

e2e-slice-38:
	$(MAKE) e2e-run-product-slice SLICE=slice-38 ACTION=slice-38 RECORD_SECONDS=120 REQUIRE_PRE_TART_REVIEW=1

e2e-slice-39:
	$(MAKE) e2e-run-product-slice SLICE=slice-39 ACTION=slice-39 RECORD_SECONDS=108 REQUIRE_PRE_TART_REVIEW=1

e2e-slice-40:
	$(MAKE) e2e-run-product-slice SLICE=slice-40 ACTION=slice-40 RECORD_SECONDS=108 REQUIRE_PRE_TART_REVIEW=1

e2e-slice-41:
	$(MAKE) e2e-run-product-slice SLICE=slice-41 ACTION=slice-41 RECORD_SECONDS=144 REQUIRE_PRE_TART_REVIEW=1

e2e-slice-42:
	$(MAKE) e2e-run-product-slice SLICE=slice-42 ACTION=slice-42 RECORD_SECONDS=132 REQUIRE_PRE_TART_REVIEW=1

e2e-slice-43:
	$(MAKE) e2e-run-product-slice SLICE=slice-43 ACTION=slice-43 RECORD_SECONDS=86 REQUIRE_PRE_TART_REVIEW=1

e2e-slice-44:
	$(MAKE) e2e-run-product-slice SLICE=slice-44 ACTION=slice-44 RECORD_SECONDS=90 REQUIRE_PRE_TART_REVIEW=1

e2e-slice-45:
	$(MAKE) e2e-run-product-slice SLICE=slice-45 ACTION=slice-45 RECORD_SECONDS=100 REQUIRE_PRE_TART_REVIEW=1

e2e-slice-46:
	$(MAKE) e2e-run-product-slice SLICE=slice-46 ACTION=slice-46 RECORD_SECONDS=120 REQUIRE_PRE_TART_REVIEW=1

e2e-slice-47:
	$(MAKE) e2e-run-product-slice SLICE=slice-47 ACTION=slice-47 RECORD_SECONDS=120 REQUIRE_PRE_TART_REVIEW=1

e2e-slice-48:
	$(MAKE) e2e-run-product-slice SLICE=slice-48 ACTION=slice-48 RECORD_SECONDS=76 REQUIRE_PRE_TART_REVIEW=1

e2e-slice-50:
	$(MAKE) e2e-run-product-slice SLICE=slice-50 ACTION=slice-50 RECORD_SECONDS=100 REQUIRE_PRE_TART_REVIEW=1

beta-package:
	/bin/bash -lc 'cd "$(CURDIR)" && \
	set -euo pipefail && \
	test -n "$(VERSION)" && \
	if [ "$(PUBLISH)" != "0" ]; then \
	    echo "beta-package requires PUBLISH=0" >&2; \
	    exit 64; \
	fi; \
	release_dir="$(RELEASE_DIR)"; \
	staging_dir="$$release_dir/WinMux-$(VERSION)"; \
	app_path="$$staging_dir/WinMux.app"; \
	cli_path="$$staging_dir/bin/winmux"; \
	zip_path="$$release_dir/WinMux-$(VERSION).zip"; \
	build_log="$$release_dir/WinMux-$(VERSION)-swift-build.log"; \
	generated_snapshot="$$(mktemp -d)"; \
	cp Sources/Common/gitHashGenerated.swift "$$generated_snapshot/gitHashGenerated.swift"; \
	cp Sources/Common/versionGenerated.swift "$$generated_snapshot/versionGenerated.swift"; \
	restore_generated() { \
	    cp "$$generated_snapshot/gitHashGenerated.swift" Sources/Common/gitHashGenerated.swift; \
	    cp "$$generated_snapshot/versionGenerated.swift" Sources/Common/versionGenerated.swift; \
	    rm -rf "$$generated_snapshot"; \
	}; \
	trap restore_generated EXIT; \
	printf "%s\n" "// FILE IS GENERATED BY Makefile" "public let winMuxAppVersion = \"$(VERSION)\"" > Sources/Common/versionGenerated.swift; \
	git_hash="$$(git rev-parse HEAD 2>/dev/null || echo SNAPSHOT)"; \
	git_short_hash="$$(git rev-parse --short HEAD 2>/dev/null || echo SNAPSHOT)"; \
	printf "%s\n" "// FILE IS GENERATED BY Makefile" "public let gitHash = \"$$git_hash\"" "public let gitShortHash = \"$$git_short_hash\"" > Sources/Common/gitHashGenerated.swift; \
	source ./script/setup.sh; \
	rm -rf "$$staging_dir" "$$zip_path"; \
	mkdir -p "$$release_dir" "$$app_path/Contents/MacOS" "$$app_path/Contents/Resources" "$$(dirname "$$cli_path")"; \
	{ \
	    echo "+ swift build -c release --product WinMuxApp"; \
	    swift build -c release --product WinMuxApp; \
	    echo "+ swift build -c release --product winmux"; \
	    swift build -c release --product winmux; \
	} >"$$build_log" 2>&1; \
	cp .build/release/WinMuxApp "$$app_path/Contents/MacOS/WinMuxApp"; \
	cp .build/release/winmux "$$cli_path"; \
	cp resources/default-config.toml "$$app_path/Contents/Resources/default-config.toml"; \
	chmod +x "$$app_path/Contents/MacOS/WinMuxApp" "$$cli_path"; \
	printf "%s\n" \
	    "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" \
	    "<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">" \
	    "<plist version=\"1.0\">" \
	    "<dict>" \
	    "    <key>CFBundleExecutable</key>" \
	    "    <string>WinMuxApp</string>" \
	    "    <key>CFBundleIdentifier</key>" \
	    "    <string>com.zimengxiong.winmux</string>" \
	    "    <key>CFBundleName</key>" \
	    "    <string>WinMux</string>" \
	    "    <key>CFBundlePackageType</key>" \
	    "    <string>APPL</string>" \
	    "    <key>CFBundleShortVersionString</key>" \
	    "    <string>$(VERSION)</string>" \
	    "    <key>CFBundleVersion</key>" \
	    "    <string>$(VERSION)</string>" \
	    "    <key>LSUIElement</key>" \
	    "    <true/>" \
	    "</dict>" \
	    "</plist>" >"$$app_path/Contents/Info.plist"; \
	codesign --force --deep --sign - --entitlements resources/WinMux.entitlements "$$app_path" >>"$$build_log" 2>&1 || true; \
	codesign --verify --deep --strict "$$app_path" >>"$$build_log" 2>&1 || true; \
	ditto -c -k --sequesterRsrc --keepParent "$$staging_dir" "$$zip_path"; \
	test -s "$$zip_path"; \
	test -x "$$app_path/Contents/MacOS/WinMuxApp"; \
	test -x "$$cli_path"; \
	printf "package_path=%s\napp_path=%s\ncli_path=%s\nbuild_log=%s\n" "$$zip_path" "$$app_path" "$$cli_path" "$$build_log"'

release:
	$(MAKE) xcodeproj VERSION="$(VERSION)" CODESIGN_IDENTITY="$(CODESIGN_IDENTITY)"
	/bin/bash -lc 'cd "$(CURDIR)" && \
	set -euo pipefail && \
	source ./script/setup.sh && \
	test -n "$(VERSION)" && \
	app_name="WinMux"; \
	release_dir="$(RELEASE_DIR)"; \
	archive_path="$$release_dir/$$app_name-$(VERSION).xcarchive"; \
	derived_data_path="$$release_dir/$$app_name-$(VERSION).deriveddata"; \
	app_path="$$archive_path/Products/Applications/$$app_name.app"; \
	zip_path="$$release_dir/$$app_name-$(VERSION).zip"; \
	log_path="$$release_dir/$$app_name-$(VERSION)-xcodebuild.log"; \
	rm -rf "$$archive_path" "$$zip_path" "$$derived_data_path"; \
	mkdir -p "$$release_dir"; \
	xcodebuild-pretty "$$log_path" \
	    -project WinMux.xcodeproj \
	    -scheme WinMux \
	    -configuration Release \
	    -archivePath "$$archive_path" \
	    -derivedDataPath "$$derived_data_path" \
	    CODE_SIGN_IDENTITY="$(CODESIGN_IDENTITY)" \
	    DEVELOPMENT_TEAM="$(DEVELOPMENT_TEAM)" \
	    CODE_SIGN_STYLE=Automatic \
	    archive; \
	test -d "$$app_path"; \
	codesign --verify --deep --strict --verbose=2 "$$app_path"; \
	codesign -dv --verbose=4 "$$app_path" 2>&1 | grep -F "Authority=$(EXPECTED_CODESIGN_AUTHORITY)" >/dev/null; \
	ditto -c -k --sequesterRsrc --keepParent "$$app_path" "$$zip_path"; \
	if [ "$(PUBLISH)" != "1" ]; then \
	    echo "Skipping GitHub release publish because PUBLISH=$(PUBLISH)"; \
	elif /usr/bin/which gh >/dev/null 2>&1; then \
	    if gh release view "$(RELEASE_TAG)" >/dev/null 2>&1; then \
	        gh release upload "$(RELEASE_TAG)" "$$zip_path" --clobber; \
	    else \
	        if [ "$(RELEASE_NOTES)" = "auto" ]; then \
	            gh release create "$(RELEASE_TAG)" "$$zip_path" --title "$$app_name $(VERSION)" --generate-notes; \
	        else \
	            gh release create "$(RELEASE_TAG)" "$$zip_path" --title "$$app_name $(VERSION)" --notes "$(RELEASE_NOTES)"; \
	        fi; \
	    fi; \
	else \
	    echo "warning: gh is not installed; built $$zip_path but did not publish a GitHub release" >&2; \
	fi'

install:
	$(MAKE) release VERSION="$(VERSION)" CODESIGN_IDENTITY="$(CODESIGN_IDENTITY)" DEVELOPMENT_TEAM="$(DEVELOPMENT_TEAM)" PUBLISH=0
	/bin/bash -lc 'cd "$(CURDIR)" && \
	set -euo pipefail && \
	app_name="WinMux"; \
	release_dir="$(RELEASE_DIR)"; \
	app_path="$$release_dir/$$app_name-$(VERSION).xcarchive/Products/Applications/$$app_name.app"; \
	install_dir="$(APP_INSTALL_DIR)"; \
	install_path="$$install_dir/$$app_name.app"; \
	test -d "$$app_path"; \
	mkdir -p "$$install_dir"; \
	osascript -e "tell application \"$$app_name\" to quit" >/dev/null 2>&1 || true; \
	rm -rf "$$install_path"; \
	ditto "$$app_path" "$$install_path"; \
	xattr -dr com.apple.quarantine "$$install_path" >/dev/null 2>&1 || true; \
	open "$$install_path"'

installed: install

clean:
	/bin/bash -lc 'cd "$(CURDIR)" && rm -rf .build .debug .deps .derived "$(RELEASE_DIR)" WinMux.xcodeproj'
