// FILE IS MAINTAINED BY HAND
// Keep parser manifests, help strings, and CLI descriptions in sync.
// Validate with: python3 script/check-command-metadata

let subcommandDescriptions = [
    ["  agent", "Query, validate, and apply agent-oriented window layout JSON"],
    ["  balance-columns", "Balance runtime widths of visible columns on a physical monitor"],
    ["  balance-sizes", "Balance sizes of all windows in the current workspace"],
    ["  card", "Page, reveal, summon, or move the deck of cards"],
    ["  close-all-windows-but-current", "On the focused workspace, close all windows but current"],
    ["  close", "Close the focused window"],
    ["  column", "Resize, collapse, expand, toggle, color, or initialize columns"],
    ["  config", "Query WinMux config options"],
    ["  cycle-column-snap-policy", "Cycle a monitor through mouse column snap policies"],
    ["  debug-windows", "Interactive command to record Accessibility API debug information to create bug reports"],
    ["  doctor", "Print diagnostics: permissions, monitors, per-app accessibility latency, manager state"],
    ["  palette", "Toggle the window switcher palette (fuzzy-search all windows)"],
    ["  enable", "Temporarily enable or disable WinMux"],
    ["  expose", "Show an overview of the display's columns or the focused card's windows"],
    ["  flatten-workspace-tree", "Flatten the tree of the focused workspace"],
    ["  focus-back-and-forth", "Switch between the current and previously focused elements back and forth"],
    ["  focus-column", "Move focus between columns"],
    ["  focus-monitor", "Focus monitor by relative direction, by order, or by pattern"],
    ["  focus", "Set focus to a window."],
    ["  fullscreen", "Toggle the fullscreen mode for the focused window"],
    ["  join-with", "Put the focused window and the nearest node in the specified direction under a common parent container"],
    ["  layout", "Change layout of the focused window to the given layout"],
    ["  list-apps", "Print the list of running applications that appears in the Dock and may have a user interface"],
    ["  list-cards", "Print cards that satisfy conditions"],
    ["  list-columns", "Print configured column viewports"],
    ["  list-exec-env-vars", "List environment variables that exec-* commands and callbacks are run with"],
    ["  list-modes", "Print a list of modes currently specified in the configuration"],
    ["  list-monitors", "Print monitors that satisfy conditions"],
    ["  list-windows", "Print windows that satisfy conditions"],
    ["  macos-native-fullscreen", "Toggle macOS fullscreen for the focused window"],
    ["  macos-native-minimize", "Minimize focused window"],
    ["  mode", "Activate the specified binding mode"],
    ["  move-mouse", "Move mouse to the requested position"],
    ["  move-node-to-card", "Move the focused window to the specified card"],
    ["  move-node-to-column", "Move the focused window or tab group to a column"],
    ["  move-node-to-monitor", "Move window to monitor targeted by relative direction, by order, or by pattern"],
    ["  move", "Move the focused window in the given direction"],
    ["  reload-config", "Reload currently active config"],
    ["  resize", "Resize the focused window"],
    ["  scene", "Switch, cycle, or name scenes on the focused display"],
    ["  set-column-snap-policy", "Set runtime mouse column snap policy"],
    ["  split", "Split focused window"],
    ["  stack-with", "Put the focused window into the same tab group as the nearest window in the specified direction."],
    ["  subscribe", "Subscribe to WinMux events and receive notifications via socket"],
    ["  swap", "Swaps the focused window with another window."],
    ["  trigger-binding", "Trigger WinMux binding as if it was pressed by user"],
    ["  volume", "Manipulate volume"],
]
