// FILE IS GENERATED FROM docs/winmux-*.adoc files
// TO REGENERATE THE FILE RUN generate.sh

let subcommandDescriptions = [
    ["  agent", "Query, validate, and apply agent-oriented window layout JSON"],
    ["  apply-zone-bindings", "Apply configured workspace bindings to zones on a physical monitor"],
    ["  balance-sizes", "Balance sizes of all windows in the current workspace"],
    ["  balance-zones", "Balance runtime widths of enabled zones on a physical monitor"],
    ["  bind-node-to-zone", "Bind the focused window or tab group to a configured zone"],
    ["  close-all-windows-but-current", "On the focused workspace, close all windows but current"],
    ["  close", "Close the focused window"],
    ["  config", "Query WinMux config options"],
    ["  cycle-zone-availability", "Cycle a monitor through named zone availability sets"],
    ["  cycle-zone-layout", "Cycle a monitor through named zone layout presets"],
    ["  cycle-zone-profile", "Cycle a monitor through named zone availability profiles"],
    ["  cycle-zone-scene", "Cycle a monitor through named zone scenes"],
    ["  cycle-zone-snap-policy", "Cycle a monitor through mouse zone snap policies"],
    ["  cycle-zone-style", "Cycle a zone through configured style tokens"],
    ["  debug-windows", "Interactive command to record Accessibility API debug information to create bug reports"],
    ["  disable-zone", "Temporarily hide a configured zone on a physical monitor"],
    ["  doctor", "Print diagnostics: permissions, monitors, per-app accessibility latency, manager state"],
    ["  palette", "Toggle the window switcher palette (fuzzy-search all windows)"],
    ["  enable", "Temporarily enable or disable WinMux"],
    ["  enable-zone", "Restore a temporarily hidden configured zone"],
    ["  export-zone-layout", "Print a TOML zone layout preset from current runtime widths"],
    ["  flatten-workspace-tree", "Flatten the tree of the focused workspace"],
    ["  focus-back-and-forth", "Switch between the current and previously focused elements back and forth"],
    ["  focus-monitor", "Focus monitor by relative direction, by order, or by pattern"],
    ["  focus-zone", "Focus the workspace active in a configured zone"],
    ["  focus", "Set focus to a window."],
    ["  fullscreen", "Toggle the fullscreen mode for the focused window"],
    ["  join-with", "Put the focused window and the nearest node in the specified direction under a common parent container"],
    ["  layout", "Change layout of the focused window to the given layout"],
    ["  list-apps", "Print the list of running applications that appears in the Dock and may have a user interface"],
    ["  list-exec-env-vars", "List environment variables that exec-* commands and callbacks are run with"],
    ["  list-modes", "Print a list of modes currently specified in the configuration"],
    ["  list-monitors", "Print monitors that satisfy conditions"],
    ["  list-windows", "Print windows that satisfy conditions"],
    ["  list-workspaces", "Print workspaces that satisfy conditions"],
    ["  list-zone-bindings", "Print runtime window and tab-group zone bindings"],
    ["  list-zones", "Print configured zone viewports"],
    ["  macos-native-fullscreen", "Toggle macOS fullscreen for the focused window"],
    ["  macos-native-minimize", "Minimize focused window"],
    ["  mode", "Activate the specified binding mode"],
    ["  move-mouse", "Move mouse to the requested position"],
    ["  move-node-to-monitor", "Move window to monitor targeted by relative direction, by order, or by pattern"],
    ["  move-node-to-project", "Move the focused window to the first workspace in the specified project"],
    ["  move-node-to-workspace", "Move the focused window to the specified workspace"],
    ["  move-node-to-zone", "Move the focused window or tab group to a configured zone"],
    ["  move-workspace-to-monitor", "Move workspace to monitor targeted by relative direction, by order, or by pattern."],
    ["  move", "Move the focused window in the given direction"],
    ["  project", "Focus the specified project"],
    ["  reload-config", "Reload currently active config"],
    ["  resize", "Resize the focused window"],
    ["  resize-zone", "Adjust runtime width of a configured zone"],
    ["  save-zone-layout", "Persist current runtime zone widths to the active config"],
    ["  set-zone-snap-policy", "Set runtime mouse zone snap policy"],
    ["  set-zone-style", "Apply a configured style token to a zone"],
    ["  split", "Split focused window"],
    ["  stack-with", "Put the focused window into the same tab group as the nearest window in the specified direction."],
    ["  subscribe", "Subscribe to WinMux events and receive notifications via socket"],
    ["  summon-workspace", "Move the requested workspace to the focused monitor."],
    ["  swap", "Swaps the focused window with another window."],
    ["  toggle-zone", "Temporarily hide or restore a configured zone"],
    ["  trigger-binding", "Trigger WinMux binding as if it was pressed by user"],
    ["  unbind-node-zone-binding", "Remove the runtime zone binding for a window or tab group"],
    ["  use-zone-availability", "Apply a named zone availability set"],
    ["  use-zone-layout", "Switch a monitor to a named zone layout preset"],
    ["  use-zone-profile", "Apply a named zone availability profile"],
    ["  use-zone-scene", "Switch a monitor to a named zone scene"],
    ["  volume", "Manipulate volume"],
    ["  workspace-back-and-forth", "Switch between the focused workspace and previously focused workspace back and forth"],
    ["  workspace", "Focus the specified workspace"],
    ["  zone", "Initialize ultrawide zone config presets"],
]
