[package]
name = "winmux-nickel-spike"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["rlib", "staticlib"]

[[bin]]
name = "spike"
path = "src/main.rs"

[dependencies]
nickel-lang-core = { version = "=0.19.0", default-features = false }
serde_json = "1"

[profile.release]
debug = false
strip = true
lto = "thin"
