import Common

extension CmdArgs {
    func toCommand() -> any Command {
        let command: any Command = switch self {
            case let args as AgentCmdArgs: AgentCommand(args: args)
            case let args as BalanceColumnsCmdArgs: BalanceColumnsCommand(args: args)
            case let args as BalanceSizesCmdArgs: BalanceSizesCommand(args: args)
            case let args as CardCmdArgs: CardCommand(args: args)
            case let args as CloseCmdArgs: CloseCommand(args: args)
            case let args as CloseAllWindowsButCurrentCmdArgs: CloseAllWindowsButCurrentCommand(args: args)
            case let args as ColumnCmdArgs: ColumnCommand(args: args)
            case let args as ConfigCmdArgs: ConfigCommand(args: args)
            case let args as CycleColumnSnapPolicyCmdArgs: CycleColumnSnapPolicyCommand(args: args)
            case let args as DebugWindowsCmdArgs: DebugWindowsCommand(args: args)
            case let args as DoctorCmdArgs: DoctorCommand(args: args)
            case let args as EnableCmdArgs: EnableCommand(args: args)
            case is ExecAndForgetCmdArgs: die("exec-and-forget is parsed separately")
            case let args as ExposeCmdArgs: ExposeCommand(args: args)
            case let args as FlattenWorkspaceTreeCmdArgs: FlattenWorkspaceTreeCommand(args: args)
            case let args as FocusCmdArgs: FocusCommand(args: args)
            case let args as FocusBackAndForthCmdArgs: FocusBackAndForthCommand(args: args)
            case let args as FocusColumnCmdArgs: FocusColumnCommand(args: args)
            case let args as FocusMonitorCmdArgs: FocusMonitorCommand(args: args)
            case let args as FullscreenCmdArgs: FullscreenCommand(args: args)
            case let args as JoinWithCmdArgs: JoinWithCommand(args: args)
            case let args as LayoutCmdArgs: LayoutCommand(args: args)
            case let args as ListAppsCmdArgs: ListAppsCommand(args: args)
            case let args as ListCardsCmdArgs: ListCardsCommand(args: args)
            case let args as ListColumnsCmdArgs: ListColumnsCommand(args: args)
            case let args as ListExecEnvVarsCmdArgs: ListExecEnvVarsCommand(args: args)
            case let args as ListModesCmdArgs: ListModesCommand(args: args)
            case let args as ListMonitorsCmdArgs: ListMonitorsCommand(args: args)
            case let args as ListWindowsCmdArgs: ListWindowsCommand(args: args)
            case let args as MacosNativeFullscreenCmdArgs: MacosNativeFullscreenCommand(args: args)
            case let args as MacosNativeMinimizeCmdArgs: MacosNativeMinimizeCommand(args: args)
            case let args as ModeCmdArgs: ModeCommand(args: args)
            case let args as MoveCmdArgs: MoveCommand(args: args)
            case let args as MoveMouseCmdArgs: MoveMouseCommand(args: args)
            case let args as MoveNodeToCardCmdArgs: MoveNodeToCardCommand(args: args)
            case let args as MoveNodeToColumnCmdArgs: MoveNodeToColumnCommand(args: args)
            case let args as MoveNodeToMonitorCmdArgs: MoveNodeToMonitorCommand(args: args)
            case let args as OpenSidebarCmdArgs: OpenSidebarCommand(args: args)
            case let args as PaletteCmdArgs: PaletteCommand(args: args)
            case let args as ReloadConfigCmdArgs: ReloadConfigCommand(args: args)
            case let args as ResizeCmdArgs: ResizeCommand(args: args)
            case let args as SceneCmdArgs: SceneCommand(args: args)
            case let args as SetColumnSnapPolicyCmdArgs: SetColumnSnapPolicyCommand(args: args)
            case let args as SplitCmdArgs: SplitCommand(args: args)
            case let args as StackWithCmdArgs: StackWithCommand(args: args)
            case is SubscribeCmdArgs: die("subscribe is handled separately")
            case let args as SwapCmdArgs: SwapCommand(args: args)
            case let args as TriggerBindingCmdArgs: TriggerBindingCommand(args: args)
            case let args as VolumeCmdArgs: VolumeCommand(args: args)
            default: die("No command implementation for \(Self.info.kind.rawValue)")
        }
        check(command.info == Self.info)
        return command
    }
}
