import Foundation

public let columnInitManagedBlockBegin = "# BEGIN WINMUX COLUMN INIT MANAGED BLOCK"
public let columnInitManagedBlockEnd = "# END WINMUX COLUMN INIT MANAGED BLOCK"
private let legacyColumnInitManagedBlockBegin = "# BEGIN WINMUX ZONE INIT MANAGED BLOCK"
private let legacyColumnInitManagedBlockEnd = "# END WINMUX ZONE INIT MANAGED BLOCK"

public enum ColumnInitConfigEditStatus: Equatable, Sendable {
    case appended
    case replaced
    case unchanged
}

public struct ColumnInitConfigEditResult: Equatable, Sendable {
    public let updatedText: String
    public let status: ColumnInitConfigEditStatus

    public init(updatedText: String, status: ColumnInitConfigEditStatus) {
        self.updatedText = updatedText
        self.status = status
    }
}

public struct ColumnInitConfigValidation: Equatable, Sendable {
    public let hasActiveColumns: Bool

    public init(hasActiveColumns: Bool) {
        self.hasActiveColumns = hasActiveColumns
    }
}

public struct ColumnInitColumnDefinition: Equatable, Sendable {
    public let id: String
    public let name: String?
    public let width: Double

    public init(id: String, name: String?, width: Double) {
        self.id = id
        self.name = name
        self.width = width
    }
}

public struct ColumnInitPresetDefinition: Equatable, Sendable {
    public let defaultColumnId: String
    public let columns: [ColumnInitColumnDefinition]

    public init(defaultColumnId: String, columns: [ColumnInitColumnDefinition]) {
        self.defaultColumnId = defaultColumnId
        self.columns = columns
    }
}

public func columnInitPresetDefinition(_ preset: ColumnInitPreset) -> ColumnInitPresetDefinition {
    switch preset {
        case .balanced:
            ColumnInitPresetDefinition(defaultColumnId: "main", columns: [
                ColumnInitColumnDefinition(id: "ref", name: "Reference", width: 0.25),
                ColumnInitColumnDefinition(id: "main", name: "Work", width: 0.50),
                ColumnInitColumnDefinition(id: "comms", name: "Comms", width: 0.25),
            ])
        case .focusOnly:
            ColumnInitPresetDefinition(defaultColumnId: "main", columns: [
                ColumnInitColumnDefinition(id: "ref", name: "Reference", width: 0.15),
                ColumnInitColumnDefinition(id: "main", name: "Work", width: 0.70),
                ColumnInitColumnDefinition(id: "comms", name: "Comms", width: 0.15),
            ])
        case .commsOpen:
            ColumnInitPresetDefinition(defaultColumnId: "main", columns: [
                ColumnInitColumnDefinition(id: "ref", name: "Reference", width: 0.20),
                ColumnInitColumnDefinition(id: "main", name: "Work", width: 0.55),
                ColumnInitColumnDefinition(id: "comms", name: "Comms", width: 0.25),
            ])
        case .dashboard:
            ColumnInitPresetDefinition(defaultColumnId: "main", columns: [
                ColumnInitColumnDefinition(id: "ref", name: "Reference", width: 0.20),
                ColumnInitColumnDefinition(id: "main", name: "Work", width: 0.45),
                ColumnInitColumnDefinition(id: "comms", name: "Comms", width: 0.20),
                ColumnInitColumnDefinition(id: "dashboard", name: "Dashboard", width: 0.15),
            ])
    }
}

public func renderColumnInitManagedBlock(
    preset: ColumnInitPreset,
    presetDefinition: ColumnInitPresetDefinition,
    monitorId: Int,
) -> String {
    var output = [
        columnInitManagedBlockBegin,
        "# Generated by: winmux column init --preset \(preset.rawValue) --write",
        "[scene.\(preset.rawValue)]",
        "display = \(monitorId)",
        "default-column = \(columnInitTomlBasicString(presetDefinition.defaultColumnId))",
        "columns = [",
    ]
    for column in presetDefinition.columns {
        var fields = [
            "id = \(columnInitTomlBasicString(column.id))",
        ]
        if let name = column.name {
            fields.append("name = \(columnInitTomlBasicString(name))")
        }
        fields.append("width = \(columnInitFormatTomlFloat(column.width))")
        output.append("    { \(fields.joined(separator: ", ")) },")
    }
    output.append("]")
    output.append(columnInitManagedBlockEnd)
    return output.joined(separator: "\n")
}

public func renderColumnInitOutput(
    title: String,
    mode: String,
    preset: ColumnInitPreset,
    monitorSummary: String,
    backupPath: String?,
    block: String,
) -> [String] {
    var output = [
        title,
        "Mode: \(mode)",
        "Preset: \(preset.rawValue)",
        "Selected monitor: \(monitorSummary)",
    ]
    if let backupPath {
        output.append("Backup: \(backupPath)")
    }
    output.append("TOML:")
    output.append(block)
    if mode == "dry-run" {
        output.append("Run with --write to update the config.")
    }
    return output
}

@MainActor
public func applyColumnInitManagedBlockToConfigText(
    to configText: String,
    block: String,
    replaceExisting: Bool,
    validateConfig: @MainActor (String) -> Result<ColumnInitConfigValidation, String>,
) -> Result<ColumnInitConfigEditResult, String> {
    if let existingRangeResult = columnInitManagedBlockRange(in: configText) {
        switch existingRangeResult {
            case .failure(let message):
                return .failure(message)
            case .success(let range):
                let existingBlock = String(configText[range])
                if existingBlock.trimmingCharacters(in: .whitespacesAndNewlines) ==
                    block.trimmingCharacters(in: .whitespacesAndNewlines)
                {
                    return .success(ColumnInitConfigEditResult(updatedText: configText, status: .unchanged))
                }
                guard replaceExisting else {
                    return .failure("A WinMux-managed column init block already exists. Re-run with --replace-existing to update it.")
                }
                var updated = configText
                updated.replaceSubrange(range, with: block)
                return validateColumnInitConfigEdit(updatedText: updated, status: .replaced, validateConfig: validateConfig)
        }
    }

    switch validateConfig(configText) {
        case .failure(let message):
            return .failure("Config must parse before column init can edit it:\n\(message)")
        case .success(let validation):
            guard !validation.hasActiveColumns else {
                return .failure(
                    "Config already has active columns. " +
                        "column init will not overwrite an existing [scene.*] layout; edit it by hand instead.",
                )
            }
    }

    let lineSeparator = configText.contains("\r\n") ? "\r\n" : "\n"
    let prefix: String
    if configText.isEmpty {
        prefix = ""
    } else if configText.hasSuffix(lineSeparator) {
        prefix = lineSeparator
    } else {
        prefix = lineSeparator + lineSeparator
    }
    let updated = configText + prefix + block + lineSeparator
    return validateColumnInitConfigEdit(updatedText: updated, status: .appended, validateConfig: validateConfig)
}

public func nextColumnInitBackupUrl(for url: URL) -> URL {
    let stamp = columnInitBackupTimestamp()
    let baseName = "\(url.lastPathComponent).backup-\(stamp)"
    let directory = url.deletingLastPathComponent()
    var candidate = directory.appending(component: baseName)
    var suffix = 2
    while FileManager.default.fileExists(atPath: candidate.path) {
        candidate = directory.appending(component: "\(baseName)-\(suffix)")
        suffix += 1
    }
    return candidate
}

public func columnInitBackupTimestamp(date: Date = Date()) -> String {
    let formatter = DateFormatter()
    formatter.calendar = Calendar(identifier: .gregorian)
    formatter.locale = Locale(identifier: "en_US_POSIX")
    formatter.timeZone = TimeZone(secondsFromGMT: 0)
    formatter.dateFormat = "yyyyMMdd'T'HHmmss'Z'"
    return formatter.string(from: date)
}

public func columnInitFormatTomlFloat(_ value: Double) -> String {
    var text = String(format: "%.6f", locale: Locale(identifier: "en_US_POSIX"), value)
    while text.last == "0" {
        text.removeLast()
    }
    if text.last == "." {
        text.append("0")
    }
    return text == "-0.0" ? "0.0" : text
}

@MainActor
private func validateColumnInitConfigEdit(
    updatedText: String,
    status: ColumnInitConfigEditStatus,
    validateConfig: @MainActor (String) -> Result<ColumnInitConfigValidation, String>,
) -> Result<ColumnInitConfigEditResult, String> {
    switch validateConfig(updatedText) {
        case .failure(let message):
            return .failure("Edited config would not parse:\n\(message)")
        case .success(let validation):
            guard validation.hasActiveColumns else {
                return .failure("Edited config did not add an active [scene.*] block")
            }
            return .success(ColumnInitConfigEditResult(updatedText: updatedText, status: status))
    }
}

private func columnInitManagedBlockRange(in configText: String) -> Result<Range<String.Index>, String>? {
    let beginMatches = columnInitMarkerRanges(
        in: configText,
        markers: [columnInitManagedBlockBegin, legacyColumnInitManagedBlockBegin],
    )
    guard let begin = beginMatches.first else { return nil }
    guard beginMatches.count == 1 else {
        return .failure("Config contains multiple WinMux-managed column init block starts")
    }

    let endMarker = begin.marker == columnInitManagedBlockBegin
        ? columnInitManagedBlockEnd
        : legacyColumnInitManagedBlockEnd
    guard let end = configText.range(of: endMarker, range: begin.range.upperBound..<configText.endIndex) else {
        return .failure("Config contains a WinMux-managed column init block start without an end marker")
    }
    let endMatches = columnInitMarkerRanges(
        in: configText,
        markers: [columnInitManagedBlockEnd, legacyColumnInitManagedBlockEnd],
    )
    guard endMatches.count == 1 else {
        return .failure("Config contains multiple WinMux-managed column init block ends")
    }
    return .success(begin.range.lowerBound..<end.upperBound)
}

private func columnInitMarkerRanges(
    in text: String,
    markers: [String],
) -> [(marker: String, range: Range<String.Index>)] {
    var matches: [(marker: String, range: Range<String.Index>)] = []
    for marker in markers {
        var searchRange = text.startIndex..<text.endIndex
        while let range = text.range(of: marker, range: searchRange) {
            matches.append((marker, range))
            searchRange = range.upperBound..<text.endIndex
        }
    }
    return matches.sorted { $0.range.lowerBound < $1.range.lowerBound }
}

private func columnInitTomlBasicString(_ value: String) -> String {
    var result = "\""
    for scalar in value.unicodeScalars {
        switch scalar {
            case "\"": result += "\\\""
            case "\\": result += "\\\\"
            case "\n": result += "\\n"
            case "\t": result += "\\t"
            case "\r": result += "\\r"
            default: result.unicodeScalars.append(scalar)
        }
    }
    result += "\""
    return result
}
